<a id="start"></a>

<span style="padding: 0 05px"></span> [ <font color = "black" size ="4" > **Ch 1.** <span style = "padding:0 2px"></span> **Conda, some useful stuff?**](#ch_1) </font>   <br/>
<span style="padding: 0 40px"></span> [ <font color = "blue" size ="2" > 1.1 <span style = "padding:0 12px">Upgrade Conda</span> ](#ref_1.1) </font>   <br/>
<span style="padding: 0 40px"></span> [ <font color = "blue" size ="2" > 1.2 <span style = "padding:0 12px">Popular keyboard shortcuts</span> ](#ref_1.2) </font>   <br/>
<span style="padding: 0 40px"></span> [ <font color = "blue" size ="2" > 1.3 <span style = "padding:0 12px">Importing libraries</span> ](#ref_1.3) </font>   <br/>


<span style="padding: 0 05px"></span> [ <font color = "black" size ="4" > **Ch 2.** <span style = "padding:0 2px"></span> **Series Module**](#ch_2) </font>   <br/>
<span style="padding: 0 40px"></span> [ <font color = "blue" size ="2" > 2.1 <span style = "padding:0 12px"></span> Creating Series from 1-D array](#ref_2.1) </font>   <br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 2.2 <span style = "padding:0 12px"></span> Intro to Attributes in Series context](#ref_2.2) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 2.3 <span style = "padding:0 12px"></span> Intro to Intro to Methods](#ref_2.3) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 2.4 <span style = "padding:0 12px"></span> Parameters and Argumemts](#ref_2.4) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 2.5 <span style = "padding:0 12px"></span> Import series with read_csv Method, separate one columns; "usecol" argument](#ref_2.5) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 2.6 <span style = "padding:0 12px"></span> Built in Python functions, used for Pandas Series](#ref_2.6) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 2.7 <span style = "padding:0 12px"></span> More from Series Attributes](#ref_2.7) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 2.8 <span style = "padding:0 12px"></span> .sort_values() method in detail](#ref_2.8) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 2.9 <span style = "padding:0 12px"></span> Make permanent change with .inplace Parameter in detail](#ref_2.9) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 2.10 <span style = "padding:0 8px"></span> .sort_index()](#ref_2.10) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 2.11 <span style = "padding:0 8px"></span> Python "in" keyword in pandas series](#ref_2.11) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 2.12 <span style = "padding:0 8px"></span> Extract values by index position](#ref_2.12) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 2.13 <span style = "padding:0 8px"></span> Extract values by index label](#ref_2.13) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 2.14 <span style = "padding:0 8px"></span> .get() method, useful for custamized NaN replaced output](#ref_2.14) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 2.15 <span style = "padding:0 8px"></span> Math methods for series object](#ref_2.15) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 2.16 <span style = "padding:0 8px"></span> .idxmax( ) and .idxmin( ) ](#ref_2.16) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 2.17 <span style = "padding:0 8px"></span> .value_counts( ) method](#ref_2.17) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 2.18 <span style = "padding:0 8px"></span> .apply( ) method](#ref_2.18) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 2.19 <span style = "padding:0 8px"></span> .map( ) method](#ref_2.19) </font><br/>

<span style="padding: 0 05px"></span> [ <font color = "black" size ="4" > **Ch 3.** <span style = "padding:0 2px"></span> **Data Frames-1**](#ch_3) </font>   <br/>


<span style="padding: 0 40px"></span> [<font color = "blue" > 3.1 <span style = "padding:0 12px"></span> Shared methods and attributes with Series objects](#ref_3.1) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 3.2 <span style = "padding:0 12px"></span> Some commonly used methods and attributes for Data Frames](#ref_3.2) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 3.3 <span style = "padding:0 12px"></span> Broadcasting Operations](#ref_3.3) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 3.4 <span style = "padding:0 12px"></span> Revision , .value_count( ) method](#ref_3.4) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 3.5 <span style = "padding:0 12px"></span> Drop the NaN values](#ref_3.5) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 3.6 <span style = "padding:0 12px"></span> .astype( );  ["category"]  and selecting type of individual list](#ref_3.6) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 3.7 <span style = "padding:0 12px"></span>  .sort_values( ) ; .sort_index( ) in Data Frame context](#ref_3.7) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 3.8 <span style = "padding:0 12px"></span> .astype( .rank( ) in Data Frame](#ref_3.8) </font><br/>

<span style="padding: 0 05px"></span> [ <font color = "black" size ="4" > **Ch 4.** <span style = "padding:0 2px"></span> **Data Frames-2**](#ch_4) </font>   <br/>
**<font color = 'green' >In this section, focus is on filtering </font>**  <br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 4.1 <span style = "padding:0 12px"></span> Useful Pandas Data Structures for saving memories](#ref_4.1) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 4.2 <span style = "padding:0 12px"></span> Extracting by boolean list](#ref_4.2) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 4.3 <span style = "padding:0 12px"></span> Filtering  with more than 1 CONDITION](#ref_4.3) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 4.4 <span style = "padding:0 12px"></span> Multiple OR conditions in single line FOR Single Column](#ref_4.4) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 4.5 <span style = "padding:0 12px"></span> Detecting null values; .isnull( ) , .notnull( )](#ref_4.5) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 4.6 <span style = "padding:0 12px"></span> .between method](#ref_4.6) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 4.7 <span style = "padding:0 12px"></span> .duplicated( ) method](#ref_4.7) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 4.8 <span style = "padding:0 12px"></span> .drop_duplicate( ) method](#ref_4.8) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 4.9 <span style = "padding:0 12px"></span> What are and how many unique items in a Column?](#ref_4.9) </font><br/>

<span style="padding: 0 05px"></span> [ <font color = "black" size ="4" > **Ch 5.** <span style = "padding:0 2px"></span> **Data Frames-3**](#ch_5) </font>   <br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 5.1 <span style = "padding:0 12px"></span> set_index( ) and reset_index( ) method:](#ref_5.1) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 5.2 <span style = "padding:0 12px"></span> Selecting rows and columns in a data Frame](#ref_5.2) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 5.3 <span style = "padding:0 12px"></span> Setting news values in a row or columns...](#ref_5.3) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 5.4 <span style = "padding:0 12px"></span> Setting news values across multiple rows...](#ref_5.4) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 5.5 <span style = "padding:0 12px"></span> Chaning Columns Names](#ref_5.5) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 5.6 <span style = "padding:0 12px"></span> Deleting row or columns](#ref_5.6) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 5.7 <span style = "padding:0 12px"></span> Selecting  n number of small/large values](#ref_5.7) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 5.8 <span style = "padding:0 12px"></span> Overall picture  where some particular scanrio is?](#ref_5.8) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 5.9 <span style = "padding:0 12px"></span> Separate copy from df](#ref_5.9) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 5.10 <span style = "padding:0 8px"></span>What is .apply() method in pandas context](#ref_5.10) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 5.11 <span style = "padding:0 8px"></span>Real example with .apply() method](#ref_5.11) </font><br/>


<span style="padding: 0 05px"></span> [ <font color = "black" size ="4" > **Ch 6.** <span style = "padding:0 2px"></span> **Working with Text Data**](#ch_6) </font>   <br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 6.1 <span style = "padding:0 12px"></span> Common String methods](#ref_6.1) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 6.2 <span style = "padding:0 12px"></span> Replace methods ](#ref_6.2) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 6.3 <span style = "padding:0 12px"></span> String with some specific ending or starting or inside, Filtering](#ref_6.3) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 6.4 <span style = "padding:0 12px"></span> Remove space from left/right sides of a string](#ref_6.4) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 6.5 <span style = "padding:0 12px"></span> Split method ](#ref_6.5) </font><br/>

<span style="padding: 0 05px"></span> [ <font color = "black" size ="4" > **Ch 7.** <span style = "padding:0 2px"></span> **Introduction to Multi Index Module**](#ch_7) </font>   <br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 7.1 <span style = "padding:0 12px"></span> Difference Between Simple and Multi-level index](#ref_7.1) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 7.2 <span style = "padding:0 12px"></span> How to access via "index" in Multi-level DF](#ref_7.2) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 7.3 <span style = "padding:0 12px"></span> How to set the index/column names of Multi-index dF ](#ref_7.3) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 7.4 <span style = "padding:0 12px"></span> Extract Rows in Multi-level DF](#ref_7.4) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 7.5 <span style = "padding:0 12px"></span> Extract Rows in Multi-level DF (example_2)](#ref_7.5) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 7.6 <span style = "padding:0 12px"></span> Taking transpose of Multi-level dF](#ref_7.6) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 7.7 <span style = "padding:0 12px"></span> Swapping the indexes levels in Multi..](#ref_7.7) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 7.8 <span style = "padding:0 12px"></span> Stack and unstack methods the dF](#ref_7.8) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 7.9 <span style = "padding:0 12px"></span> Pivot the data with pivot method](#ref_7.9) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 7.10 <span style = "padding:0 8px"></span> Slightly different: pivot_table( ) method for more universal use](#ref_7.10) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 7.11 <span style = "padding:0 8px"></span> Reducing the aggregated date to simple tabular form with pd.melt( )](#ref_7.11) </font><br/>


<span style="padding: 0 05px"></span> [ <font color = "black" size ="4" > **Ch 8.** <span style = "padding:0 2px"></span> **Grouping via .groupby( )method**](#ch_8) </font>   <br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 8.1 <span style = "padding:0 8px"></span> what is groupby method in general](#ref_8.1) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 8.2 <span style = "padding:0 8px"></span> How to extract each sector](#ref_8.2) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 8.3 <span style = "padding:0 8px"></span> Now , what methods are available to this groupby object ](#ref_8.3) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 8.4 <span style = "padding:0 8px"></span> Grouping via multiple columns ](#ref_8.4) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 8.5 <span style = "padding:0 8px"></span> Iterating through groupby( ) ](#ref_8.5) </font><br/>


<span style="padding: 0 05px"></span> [ <font color = "black" size ="4" > **Ch 9.** <span style = "padding:0 2px"></span> **Merging, Joining and concatination**](#ch_9) </font>   <br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 9.1 <span style = "padding:0 8px"></span> Vertical Concatination](#ref_9.1) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 9.2 <span style = "padding:0 8px"></span> Adding another layer of before index](#ref_9.2) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 9.3 <span style = "padding:0 8px"></span> Directly append one data set](#ref_9.3) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 9.4 <span style = "padding:0 8px"></span> Inner and Outer Joins ( Unions and Intersections of two data sets )](#ref_9.4) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 9.5 <span style = "padding:0 8px"></span> Left Join , its like Horizontal concatination technique ](#ref_9.5) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 9.6 <span style = "padding:0 8px"></span> Situation when columns names are different.. how to merge? ](#ref_9.6) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 9.7 <span style = "padding:0 8px"></span> Merging by index](#ref_9.7) </font><br/>

<span style="padding: 0 05px"></span> [ <font color = "black" size ="4" > **Ch 10.** <span style = "padding:0 2px"></span> **Input and Output Module**](#ch_10) </font>   <br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 10.1 <span style = "padding:0 8px"></span> Accessing a URL data in Pandas and actively converting to list,series or comman separated data](#ref_10.1) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 10.2 <span style = "padding:0 8px"></span> Writing csv file and export it... with pd.read_cev() method ](#ref_10.2) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 10.3 <span style = "padding:0 8px"></span>  Importing excel file](#ref_10.3) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 10.4 <span style = "padding:0 8px"></span> Writing file in Excel format](#ref_10.4) </font><br/>

<span style="padding: 0 05px"></span> [ <font color = "black" size ="4" > **Ch 11.** <span style = "padding:0 2px"></span> **Introduction to plotting with matplotlib**](#ch_11) </font>   <br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 11.1 <span style = "padding:0 8px"></span> Getting stock data and plot it simply](#ref_11.1) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 11.2 <span style = "padding:0 8px"></span> Template selection and plotting types](#ref_11.2) </font><br/>
<span style="padding: 0 40px"></span> [<font color = "blue" > 11.3 <span style = "padding:0 8px"></span> Different types of plots](#ref_11.3) </font><br/>



***

[Back to Top](#start)

### Ch 1.Conda, some useful stuff?  <a id="ch_1"></a>

**<font color = 'green' >Inside Anaconda (Python Distribution), 
there is one library called <font color ="red" size ="3"> <u>conda</u> </font>.This library is there to install other libraries for Anaconda distribution.</font>**

#### <font color = "navy" >1.1 Upgrade Conda</font>  <a id="ref_1.1"></a>

**<font color = "blue" >1.1.1 Updating Anaconda itself</font>** <br>
Use Following commands on terminal to update conda:
    1. source activate root
    2. conda update conda ;  (updating itself)

This will just download these packages , unpack and install in respective libraries.


**<font color = "blue" >1.1.2 Also update/install the markdown:</font>** 
    1. conda install markdown 

Nice thing about install it, if already there then it will update otherwise install the latest version

**<font color = "blue" >1.1.3 Also update/install the bottleneck: </font>** 
    1. conda install bottleneck 

This is speed accelration processes

**<font color = "blue" >1.1.4 Also update/install the numexpr: </font>** 
    1. conda install numexpr 

Another accelration library

**<font color = "blue" >1.1.5 Also update/install the matplotlib:</font>** 
    1. conda install matplotlib 

**<font color = "blue" >1.1.6 Update all installed conda libraries:</font>**
    1. conda update --all 

[Back to Top](#start)

#### <font color = "navy" >2. Popular keyboard shortcuts</font>  <a id="ref_1.2"></a>

Firt of all press escape key and then all of the keyboard shortcut would work
1. h  &nbsp;&nbsp;&nbsp;  (for help)
2. x  &nbsp;&nbsp;&nbsp;  (cut a cell)
3. b  &nbsp;&nbsp;&nbsp;  (b for  below; insert cell below)
4. shift + enter &nbsp;&nbsp;&nbsp; (cell executation)

[Back to Top](#start)

#### <font color = "navy" >3. Importing libraries</font>  <a id="ref_1.3"></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
pd.__version__

'0.23.4'

In [3]:
np.__version__

'1.15.4'

[Back to Top](#start)

### Ch 2. Series Module <a id="ch_2"></a>

#### <font color = "navy" >2.1 Creating Series from 1-D array </font> <a id="ref_2.1"></a>

- **<font color = 'blue' >2.1.1 Defining a series from 1-D Python Numeric and string array</font>**

In [1]:
%reset -f
import pandas as pd

<font color = "green" size ="3" > String type array <br/> Special attention: Index and dtype </font> <br/>
<font color = "olive"> <u> Although we can initiate index but for the time being... its skipped </u></font>

- <font color = 'blue' > Example-1</font>

In [12]:
ice_creams = ["vanina","blue_berry","licoris","chocolate","badam"]
pd.Series(ice_creams)  # pandas create me a brand new series object
# look at dtype
pass

- <font color = 'blue' > Example-2</font>

In [13]:
lottery = [4,8,26,101,546]
pd.Series(lottery)
# look at dtype
pass

<font color = "olive"> <u> Everytime series generates the index, <br/> if not provided it starts from zero like above </u></font>

- **<font color = 'blue' >2.1.2 Series of Boolean entities </font>**

In [14]:
bol = [True,False,True,True,True,True,False,False,False,True]
pd.Series(bol)
pass

- **<font color = 'blue' >2.1.3 A Series object from Python dict </font>**

<font color = "green" size ="3" > String type array <br/> Special attention: Index and dtype </font> <br/>
<font color = "olive"> <u> Although we can initiate index but for the time being... its skipped </u></font>

In [6]:
%reset -f
import pandas as pd

- <font color = 'blue' > Example-1</font>

In [15]:
dic_1 = {
       "one":"aik",
        "two":"doo",
        "three":"teen"
}
# first just convert it to the pandas series(1d object)
pd.Series(dic_1)
pass

- <font color = 'blue' > Example-2</font>

In [16]:
dic_2 = {
       "one":1,
        "two":2,
        "three":3
}
# first just convert it to the pandas series(1d object)
pd.Series(dic_2)
pass


[Back to Top](#start)

<font color = "olive"> <u>Keep in mind,series can also have a multiple identical index but funcnalities then somehow reduced<u/> </font>

#### <font color = "navy" >2.2 Intro to Attributes in Series context</font>  <a id="ref_2.2"></a>

<font color = "olive"> <u> Attributes don't need paranthesis () ... just thats it <u/> </font>

<font color = "green" size ="3" > Most intensively used are .values,.index,.dtype </font> </font>

In [13]:
about_me = ["Charming","Handsome","Smart","Barilliant","Humble"]
s = pd.Series(about_me)

In [14]:
s.values

array(['Charming', 'Handsome', 'Smart', 'Barilliant', 'Humble'],
      dtype=object)

In [15]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [16]:
s.dtype

dtype('O')

[Back to Top](#start)

#### <font color = "navy" >2.3 Intro to Methods</font>  <a id="ref_2.3"></a>

<font color = "olive"> <u> Attributes  need paranthesis () ... just thats it <u/> </font> <br/>
<font color = "green" size ="3" > Three very basic are: .sum() , .product() , .mean() </font> </font>

In [27]:
prices = [1,2,3,4,5]
p= pd.Series(prices)

In [28]:
p.sum()
pass

In [29]:
p.product()
pass

In [30]:
p.mean()
pass

[Back to Top](#start)

#### <font color = "navy" >2.4 Parameters and Argumemts</font>  <a id="ref_2.4"></a>

In [32]:
%reset -f
import pandas as pd

In [33]:
fruits = ["Apple","Orage","Banana","Kiwi"]
days_no = [1,2,3,4]

- <font color = 'blue' > Style-1</font>

In [35]:
f1 = pd.Series(fruits,days_no)   
f1
# see, days_no we provide second but its taking it as indexing
# and dtype is according to data (which is string = object), 
pass

- <font color = 'blue' > Style-2</font>

In [36]:
#style-2
f1 = pd.Series(days_no, index = fruits )
f1
pass

<font color = "olive" ><u>Keep in mind,series can also have a multiple identical index</u> <br>
But some operations are not possible in such case</font> 

- <font color = 'blue' > Style-3</font> <br/>
<font color = "green" size ="3" > I'll stick to this </font>

In [37]:
fruits = ["Apple","Orage","Banana","Kiwi","Badam"]
days = ["Monday","Tuesday","Wednesday","Thursday","Monday"]

In [38]:
f2 = pd.Series(data = fruits, index = days)
f2
pass

[Back to Top](#start)

#### <font color = "navy" >2.5 Import series with read_csv Method, separate one columns; "usecol" argument</font> <a id="ref_2.5"></a>

In [3]:
%reset -f
import pandas as pd

In [55]:
pokemon = pd.read_csv("files_for_pandas/pokemon.csv")

In [56]:
pokemon.head(6)
pass

<font color = "olive"> <u>We want to single out the "Pokemon" column only so use "usecols = ["~~~"]"</u></font>

In [42]:
pokemon = pd.read_csv("files_for_pandas/pokemon.csv", usecols = ["Pokemon"])
google = pd.read_csv("files_for_pandas/google_stock_price.csv", squeeze=True)

In [47]:
pokemon.head(10)
pass

In [44]:
google.head(10)
pass

<font color = "olive"> <u>Did you notice its still showing as a 2-D data object, so add squeeze paramter</u></font>

In [59]:
pokemon = pd.read_csv("files_for_pandas/pokemon.csv", usecols = ["Pokemon"],squeeze = True)

In [60]:
pokemon.head(4)
pass

[Back to Top](#start)

#### <font color = "navy" >2.6 Built in Python functions, used for Pandas Series</font> <a id="ref_2.6"></a>

- **<font color = 'blue' >2.6.1 len(object_name) ;</font>**  # Total # of rows

In [61]:
len(pokemon)

721

- **<font color = "blue" >2.6.2 type(object_name) ;</font>**  # type of passing object

In [62]:
type(pokemon)

pandas.core.series.Series

- **<font color = "blue" >2.6.3 dir(object_name) ;</font>**  # All available methods for this object

In [63]:
dir(google)
pass

- **<font color = "blue" >2.6.4 sorted(object_name) ;</font>**  # sorting of an object

In [64]:
sorted(google)
pass

- **<font color = "blue" >2.6.5 dict(object_name) ;</font>**  # dictionary representation, index = built in 0,1,2,..; values = object

In [65]:
dict(google)
pass

- **<font color = "blue" >2.6.6 max/min(object_name) ;</font>**  # maximum or minimum of Series object

In [66]:
max(google)

782.22

[Back to Top](#start)

#### <font color = "navy" >2.7 More from Series Attributes</font>  <a id="ref_2.7"></a>

<font color = "green" size ="2" > Basically think like a instance method under Series class and beautified with @property decoraters <br>
so calling is like **object_name.method** without () </font> </font>

- **<font color = "blue" > 2.7.1: .values attribute</font>**  # Give all the value of a series object <br>

In [67]:
google.values

array([ 50.12,  54.1 ,  54.65, ..., 773.18, 771.61, 782.22])

- **<font color = "blue" > 2.7.1: .index attribute</font>** 

In [68]:
google.index

RangeIndex(start=0, stop=3012, step=1)

- **<font color = "blue" > 2.7.2: .dtype attribute</font>** 

In [69]:
google.dtype

dtype('float64')

- **<font color = "blue" > 2.7.3: .is_unique attribute</font>** 

In [70]:
google.is_unique

False

- **<font color = "blue" > 2.7.4: .ndim attribute</font>** # for dimension information

In [71]:
pokemon.ndim

1

- **<font color = "blue" > 2.7.5: .shape attribute</font>** # for dimension information

In [72]:
google.shape

(3012,)

- **<font color = "blue" > 2.7.6: .size attribute</font>** # for dimension information

In [73]:
google.size

3012

- **<font color = "blue" > 2.7.6: .name attribute</font>** # even used for chaning names

In [74]:
pokemon.name

'Pokemon'

[Back to Top](#start)

#### <font color = "navy" >2.8: .sort_values() method in detail</font>  <a id="ref_2.8"></a>

In [48]:
%reset -f
import pandas as pd

In [49]:
pokemon = pd.read_csv("files_for_pandas/pokemon.csv",usecols = ["Pokemon"],squeeze = True)

<font color = "olive"> <u>First just check out our series</u></font>

In [50]:
pokemon.head(4)
pass

<font color = "olive"> <u>Now ascending = True, although its by default</u></font>

In [51]:
pokemon.sort_values(ascending=True).head()
pass

<font color = "olive"> <u> But it did not change the orignal series permanently, have a look</u></font>

In [52]:
pokemon.head(8)
pass

<font color = "olive"> <u>Similalry we can go for ascending = Flase, for revser order</u></font>

In [53]:
pokemon.sort_values(ascending=False).head()
pass

<font color = "olive"> <u>Again as expect, it didn't change the series permanently </u></font>

In [54]:
pokemon.head(8)
pass

[Back to Top](#start)

#### <font color = "navy" >2.9: Make permanent change with .inplace Parameterin detail</font>
**It replace the sorted values into the orignal data list**  <a id="ref_2.9"></a>

In [15]:
%reset -f
import pandas as pd

In [16]:
pokemon = pd.read_csv("files_for_pandas/pokemon.csv",usecols=["Pokemon"],squeeze=True)

In [18]:
pokemon.head(4)
pass

<font color = "olive"> <u>sort google in ascending=False order</u></font>

In [61]:
pokemon.sort_values(ascending=False,inplace = True)
pass

<font color = "olive"> <u>Now the change is permamnet </u></font>

In [57]:
pokemon.head(6)
pass

[Back to Top](#start)

#### <font color = "navy" >2.10: .sort_index() </font>
This is a complementry method of .sort.values() method  <a id="ref_2.10"></a>

In [62]:
%reset -f
import pandas as pd

In [63]:
google = pd.read_csv("files_for_pandas/google_stock_price.csv",squeeze=True)

<font color = "olive"> <u>Just take a look on the series object</u></font>

In [71]:
google.head(4)
pass

<font color = "olive"> <u>Sort according to ascending index order</u></font>

In [65]:
google.sort_index(ascending=False,inplace=True)

In [72]:
google.head(8)
pass

<font color = "olive"> <u>Hmmm,,,, lets sort the value sof google series</u></font>

In [67]:
google.sort_values(ascending=True,inplace=True)
pass

<font color = "olive"> <u>Now look here, values are sorted but the index is shuffled</u></font>

In [73]:
google.head(9)
pass

<font color = "olive"> <u>To get the orignal shape of the date as in file, 
 we can do .index_sorting() sorting</u></font>

In [69]:
google.sort_index(ascending=True,inplace=True)
pass

In [74]:
google.head(9)
pass

[Back to Top](#start)

#### <font color = "navy" >2.11: Python "in" keyword in pandas series </font>  <a id="ref_2.11"></a>

- **<font color = "blue"> <u> Example Python in-key word <u/></font>**

In [76]:
# for example
3 in [1,2,3,4,5,6,7]
pass

In [77]:
%reset -f
import pandas as pd
pokemon = pd.read_csv("files_for_pandas/pokemon.csv",usecols=["Pokemon"],squeeze=True)
google = pd.read_csv("files_for_pandas/google_stock_price.csv",squeeze=True)

In [79]:
pokemon.head(4)
pass

<font color = "olive"> <u>Now lets apply like Bulbasaur in Pokemon </u></font>

In [80]:
"Bulbasaur" in pokemon
pass

<font color = "olive"> <u>Why False? , its because be default its is checking in the index
we can proove that by looking in to <br>
100 in pokemon <br>
here you will get True so in principle this syntax is equal to following syntax <br>
100 in pokemon.index
</u></font>

In [81]:
100 in pokemon
pass

In [82]:
100 in pokemon.index
pass

<font color = "olive"> <u> So, solution is check "Bulbasaur"" in the pokemon.values
</u></font>

In [83]:
"Bulbasaur" in pokemon.values
pass

[Back to Top](#start)

#### <font color = "navy" >2.12: Extract values by index position </font>  <a id="ref_2.12"></a>

In [273]:
%reset -f
import pandas as pd

In [274]:
pokemon = pd.read_csv("files_for_pandas/pokemon.csv",usecols=["Pokemon"],squeeze=True)
google = pd.read_csv("files_for_pandas/google_stock_price.csv",squeeze=True)

In [96]:
pokemon.head(7)
pass

- **<font color = "blue"> <u> Accessing single value<u/> </font>**

In [84]:
pokemon[0]
pass

In [85]:
pokemon[5]
pass

- **<font color = "blue"> <u> Accessing Multiple values <u/> </font>**

In [93]:
pokemon[[100,200,300]]
pass

- **<font color = "blue"> <u> Accessing values in range <u/> </font>**

In [94]:
pokemon[12:24]
pass

In [95]:
pokemon[-18:-12]
pass

[Back to Top](#start)

#### <font color = "navy" >2.13: Extract values by index label </font>  <a id="ref_2.13"></a>

In [88]:
%reset -f
import pandas as pd

<font color = "olive"> <u> we can set which column we need as an index
</u></font>

In [89]:
poke_modified = pd.read_csv("files_for_pandas/pokemon.csv",index_col="Pokemon",squeeze = True)
poke_modified.sort_index(inplace = True)

In [90]:
poke_modified.head(9)
pass

- **<font color = "blue"> <u> Accessing single value<u/> </font>**

In [91]:
poke_modified["Charizard"]
pass

<font color = "olive"> <u> This time see, even the last item is included
</u></font>

- **<font color = "blue"> <u> Accessing Multiple values<u/> </font>**

In [98]:
poke_modified[["Charizard","Blastoise"]]
pass

In [93]:
poke_modified.reindex([["Charizard","mian"]])
pass

- **<font color = "blue"> <u> Accessing index values by range<u/> </font>**

In [97]:
poke_modified["Blastoise":"Charizard"]
pass

<font color = "olive"> <u> Interesting thing is , we can still access with index
</u></font>

In [94]:
poke_modified[0]
pass

In [86]:
poke_modified[0:10]
pass

[Back to Top](#start)

#### <font color = "navy" >2.14: .get() method, useful for custamized NaN replaced output </font>  <a id="ref_2.14"></a>

In [1]:
%reset -f
import pandas as pd

In [2]:
poke_modified = pd.read_csv("files_for_pandas/pokemon.csv",index_col="Pokemon",squeeze = True)
poke_modified.sort_index(inplace = True)

In [95]:
poke_modified.head()
pass

In [96]:
poke_modified.get(key="Ivysaur",default = "Not availa" )
pass

In [85]:
poke_modified.get(key=["Ivysaur","Bulbasaur","Charmeleon"],default = "Not availa" )
pass

In [364]:
# poke_modified.get(["Charizard":"Blastoise"])

[Back to Top](#start)

#### <font color = "navy" >2.15: Math methods for series object </font>  <a id="ref_2.15"></a>

In [98]:
%reset -f
import pandas as pd

In [99]:
google = pd.read_csv("files_for_pandas/google_stock_price.csv",squeeze = True)

<font color = "olive"> <u> Just to remind our self that we are dealing with floating numbers
</u></font>

- **<font color = "blue"> <u>.count() method <u/></font>**

<font color = "green" size ="4" > .count() method excludes the NaN values unlike the len method </font>

In [100]:
google.count()
pass

In [101]:
len(google)
pass

- **<font color = "blue"> <u>.sum( ) method <u/></font>**

In [103]:
google.sum()
pass

- **<font color = "blue"> <u>.mean( ) method <u/></font>**

In [102]:
google.mean()
pass

- **<font color = "blue"> <u> .std( ) method <u/></font>**

In [104]:
google.std()   # standard deviation
pass

- **<font color = "blue"> <u> .min/max( ) method <u/></font>**

In [105]:
google.min()
pass

- **<font color = "blue"> <u> .median( ) method <u/></font>**

In [106]:
google.median()
pass

- **<font color = "blue"> <u> .mode( ) method <u/></font>**

<font color = "olive"> <u> Value that occurs THE MOST frequently
</u></font>

In [107]:
google.mode()
pass

- **<font color = "blue"> <u> .describe( ) <u/></font>**

<font color = "olive"> <u> It provides the sumaary like below
</u></font>

In [79]:
google.describe()
pass

[Back to Top](#start)

#### <font color = "navy" >2.16: .idxmax( ) and .idxmin( ) </font>  <a id="ref_2.16"></a>

<font color = "olive"> <u> It give the index of max or min
</u></font>

In [404]:
%reset -f
import pandas as pd

In [405]:
google = pd.read_csv("files_for_pandas/google_stock_price.csv",squeeze = True)

In [78]:
google.head(3)
pass

<font color = "olive"> <u> Just start with .max() method
</u></font>

In [108]:
google.max()
pass

In [109]:
google.min()
pass

In [110]:
google.idxmax()   # index of 3011 is storing the max= 782.22 value
pass

In [111]:
google[3011]
pass

In [112]:
google.idxmin()   # index of 11 is storing the min= 49.95 value
pass

In [113]:
google[11]
pass

<font color = "olive"> <u> Now just take the advantage of combining <br>
.idxmiax()/min() with .max()/.min()

</u></font>

In [114]:
google[google.idxmax()]   # google[here I need index]; .idxmax() method only give index
pass

[Back to Top](#start)

#### <font color = "navy" >2.17: .value_counts( ) method </font>  <a id="ref_2.17"></a>

In [254]:
%reset -f
import pandas as pd

In [255]:
pokemon = pd.read_csv("files_for_pandas/pokemon.csv", index_col = "Pokemon", squeeze = True)
pokemon.head(3)
pass

In [256]:
pokemon.value_counts()
pass

<font color = "olive"> <u> Now since its a series, we can start calling on different methods on it

</u></font>

In [257]:
pokemon.value_counts().sum()

721

In [259]:
pokemon.value_counts(ascending=True)
pass

[Back to Top](#start)

#### <font color = "navy" >2.18: .apply( ) method </font>  <a id="ref_2.18"></a>

<font color = "olive"> <u> Its like the Python map function 

</u></font>

In [116]:
%reset -f
import pandas as pd

In [117]:
google = pd.read_csv("files_for_pandas/google_stock_price.csv",squeeze = True)

In [118]:
def classify(num):
    if num < 100:
        return "OK"
    if num >=300 and num < 500:
        return "Good"
    if num > 500:
        return "Awsome"

In [119]:
google.apply(classify).tail()
pass

[Back to Top](#start)

#### <font color = "navy" > 2.19: .map( ) method </font>  <a id="ref_2.19"></a>

In [120]:
%reset -f
import pandas as pd

In [121]:
pok_key = pd.read_csv("files_for_pandas/pokemon.csv",usecols=["Pokemon"],squeeze=True)
pok_key.head()
output = None

In [122]:
pok_value = pd.read_csv("files_for_pandas/pokemon.csv", index_col="Pokemon", squeeze = True)
pok_value.head()
pass

In [123]:
pok_key.map(pok_value).head()
output = None

<font color = "olive" > <u> it takes the value of first structure and compare with the
    index of second structure and then return as 
    index of first : values of second (at same index)
    </u></font>
    

[Back to Top](#start)

### Ch 3. Data Frames-1  <a id="ch_3"></a>

<font color = "olive" >  <u> Series --> 1-d ; Data Frame ---> 2-D </u> </font>


#### <font color = "navy" > 3.1: Shared methods and attributes with Series objects </font>    <a id="ref_3.1"></a>

In [1]:
%reset -f
import pandas as pd

In [2]:
nba = pd.read_csv("files_for_pandas/nba.csv")

- **<font color = "blue" > 3.1.1: .head( ) method</font>** 

In [174]:
nba.head(2)
output = None

- **<font color = "blue" > 3.1.2: .tail( ) method </font>**

In [175]:
nba.tail(2)
output = None

- **<font color = "blue" > 3.1.2: .index , shape , size  ; attributes </font>**

In [176]:
# nba.index
nba.size
# nba.shape

4122

- **<font color = "blue" > 3.1.2: .values attributes </font>**

In [177]:
nba.values
output = None

<font color = "olive" >  <u> Here it shows some of the initial and 
final lines stored in an array, each of which is an stored inside another array, 
so overall its a 2D object</u> </font>

[Back to Top](#start)

#### <font color = "navy" > 3.2: Some commonly used methods and attributes for Data Frames </font>  <a id="ref_3.2"></a>

In [21]:
%reset -f
import pandas as pd

In [22]:
nba = pd.read_csv("files_for_pandas/nba.csv")
nba.head()
output = None

- **<font color = "blue" > 3.2.1: columns and axes attributes </font>**

In [4]:
nba.index
nba.columns
pass

In [7]:
# axes combine both index and column... so its very useful
nba.axes
output = None

<font color = "olive" >  <u> There is a minute difference between them, <br/>
.columns only show names <br/>
.axes show the index range as well along with column names    </u> </font>

 - **<font color = "blue" > 3.2.2: Overall scanirio of each column </font>**

In [29]:
# nba.info() 

  - **<font color = "blue" > 3.2.3: Selecting single column </font>**

In [246]:
nba["Name"]
nba["Team"]
output = None

 <font color = "olive" >  <u> pay attention, this single column is of type Series which we 
    can store in a dofferent variable and goon with series properties</u> </font>

In [247]:
type(nba["Name"])      # nba["Name"].dtype

pandas.core.series.Series

  - **<font color = "blue" > 3.2.4: Selecting more than 1 column </font>**

In [248]:
nba[ ["Name","Team"] ].head()
output = None

 - **<font color = "blue" > 3.2.5: adding column at the end of Data Frame </font>**

In [9]:
nba["at the end"] = "after Salary"
# nba.head(3)

 - **<font color = "blue" > 3.2.6: adding column at specific location </font>**

In [3]:
nba.insert(loc = 2, column = "Country", value = "Germany")

In [20]:
nba.head(3)
pass

<font color = "green" size ="2" > Instead of a particular value we can also insert a full columns in same way </font>

In [23]:
# suppose we create two data frames from nba...
nba.head()
output = None

In [19]:
df1 = nba[["Name","Team","College"]]
s = nba["Salary"]

In [27]:
df1.head()
output = None

In [25]:
s.head()
pass

In [24]:
# since we have to insert in df1, lets first check the .axes method
df1.axes
pass

In [21]:
df1.insert(loc = 2,column="borrow_salary",value=s)

In [23]:
df1.head()
output = None

[Back to Top](#start)

#### <font color = "navy" > 3.3: Broadcasting Operations </font>  <a id="ref_3.3"></a>

In [2]:
%reset -f
import pandas as pd

In [3]:
nba = pd.read_csv("files_for_pandas/nba.csv")

 - **<font color = "blue" > 3.3.1: .add( ) ; .sub( ) ; .mul( ) ; .div( ) operation </font>** <br/>
 <font color = "blue" >  addition, subtration, multiply, division </font>

In [25]:
nba.head(3)
pass

In [5]:
nba["Salary"].fillna(value = 0, inplace = True)
# Detail is coming shortly

In [20]:
nba["Salary"].head(4)
pass

In [21]:
nba["Salary"].div(1000000).head(5)
pass

[Back to Top](#start)

#### <font color = "navy" > 3.4: Revision , .value_count( ) method </font>  <a id="ref_3.4"></a>

 <font color = "olive" >  <u> This method is only available to Series </u> </font>

In [2]:
%reset -f
import pandas as pd

In [3]:
nba = pd.read_csv("files_for_pandas/nba.csv")

In [17]:
nba.head(4)
pass

In [18]:
nba["Height"].value_counts().head(4)
pass

[Back to Top](#start)

#### <font color = "navy" > 3.5: Drop the NaN values </font>  <a id="ref_3.5"></a>

In [17]:
%reset -f
import pandas as pd

In [18]:
nba = pd.read_csv("files_for_pandas/nba.csv")

In [25]:
nba.head(4)
output = None

 - **<font color = "blue" > 3.5.1: drop a rows | column containing any Nan value   </font>**

<font color = "green" size ="3" > Things to remember: <br/> 
1). Here I are directly calling .dropna() method on whole data frame <br/>
2). axis =0 means, along index... i.e. horizontal <br/>
3). Later I will apply this method on one specific column as well.. instead of whole dF </font>

In [26]:
nba.dropna(axis = 0, how = 'any').head(5)
output = None

<font color = "olive" >  <u> Look at the index , some of them are removed ; 
    but we didn't set inplace parameter = True</u> </font>

In [29]:
nba.head(3)
nba.tail(2)
output = None

In [30]:
nba.dropna(axis = 0, how = "all").tail(3)
output = None

In [42]:
nba.head(3)
pass

In [16]:
nba.Salary.head(5)
pass

<font color = "green" size ="3" >  Here I will apply this method on one specific column as well.. instead of whole dF <br/>
Pay attention on another paramter "subset" </font>

In [41]:
nba.dropna(subset = ["Salary"]).head(4)
pass

<font color = "olive" >  <u> Look at the index , some of them are removed ; 
    but we didn't set inplace parameter = True</u> </font>

 - **<font color = "blue" > 3.5.2: Filling NaN values with something custamised   </font>**

<font color = "green" size ="3" >  Complementry methid with dropna.. <br/>
Sometime we don't want to drop ... but fill with something else like 0 or etc... </font>

In [17]:
%reset -f
import pandas as pd

In [18]:
nba = pd.read_csv("files_for_pandas/nba.csv")

In [101]:
nba["College"][1:8] ; pass

In [102]:
nba["College"].fillna(value = "No Affiliation")[3:8] ; pass

[Back to Top](#start)

#### <font color = "navy" > 3.6: .astype( );  ["category"]  and selecting type of individual list</font>  <a id="ref_3.6"></a>

In [28]:
%reset -f
import pandas as pd

In [29]:
nba = pd.read_csv("files_for_pandas/nba.csv")

In [30]:
nba.head(4)
# output = None

Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   

             College     Salary  
0              Texas  7730337.0  
1          Marquette  6796117.0  
2  Boston University        NaN  
3      Georgia State  1148640.0

 - **<font color = "blue" > Chaning type of a particular Column   </font>** 

<font color = "olive" >  <u> Here you can see the age is float, although it was entered as "int" 
 the reason behing is, if last row is complete NaN, so panda inherently convert every int to float ;
 BUT before doing this, first remove permanently the Nan from the bottom   
    
</u> </font>

In [32]:
nba.info() ; pass

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
Name        457 non-null object
Team        457 non-null object
Number      457 non-null float64
Position    457 non-null object
Age         457 non-null float64
Height      457 non-null object
Weight      457 non-null float64
College     373 non-null object
Salary      446 non-null float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB


In [83]:
nba.dropna(how = "all",inplace = True)
nba.tail(3)
pass

In [94]:
nba["Age"].astype("int")[12:15]
nba["Number"].astype("int")
output = None
# later we can assign it like followung way 

```python
nba["Age"] = nba["Age"].astype("int")
nba["Number"] = nba["Number"].astype("int")
```

<font color = "green" size ="3" >  We can even do with multiple columns at the same time like below </font>

```python
df[["Age","Weight"]] = df[["Age","Weight"]].astype(dtype = "int")
```

 - **<font color = "blue" > If some values are just repeating in a Series   </font>**

In [88]:
nba["Position"].nunique()
nba["Position"].unique()

array(['PG', 'SF', 'SG', 'PF', 'C'], dtype=object)

In [90]:
nba["Position"] = nba["Position"].astype("category")

In [31]:
# nba.info()
# look at the memory usage

[Back to Top](#start)

#### <font color = "navy" > 3.7: .sort_values( ) ; .sort_index( ) in Data Frame context</font>  <a id="ref_3.7"></a>

In [ ]:
%reset -f
import pandas as pd

In [ ]:
nba = pd.read_csv("files_for_pandas/nba.csv")

In [114]:
nba.head(6)
pass

 - **<font color = "blue" > Sorting according to single column   </font>**

In [115]:
nba.sort_values("Team",ascending = True, na_position = "last").head(4)
pass

 - **<font color = "blue" > Sorting w.r.t multiple columns   </font>**

In [127]:
nba.sort_values(["Team","Name"],ascending = [True,False], na_position = "last", inplace = True)
nba.head(5)
pass

 - **<font color = "blue" > Sorting w.r.t index  </font>**

In [126]:
nba.sort_index(ascending = True, inplace = True)
nba.head(6)
pass

[Back to Top](#start)

#### <font color = "navy" > 3.8: .rank( ) in Data Frame </font>  <a id="ref_3.8"></a>

In [14]:
%reset -f
import pandas as pd

In [15]:
nba = pd.read_csv("files_for_pandas/nba.csv")

In [16]:
nba.head(6)
pass

In [17]:
nba["Salary"].fillna(value = 0,inplace = True)
nba[0:3] 
pass

In [18]:
nba["Salary Rank"] = nba["Salary"].rank(ascending = False).astype("int")

In [19]:
nba[0:6]  
pass

[Back to Top](#start)

### Ch 4. Data Frames-2 <a id="ch_4"></a>

**<font color = 'green' >In this section, focus is on filtering </font>** 

#### <font color = "navy" > 4.1: Useful Pandas Data Structures for saving memories </font>  <a id="ref_4.1"></a>

In [1]:
%reset -f
import pandas as pd

In [2]:
df = pd.read_csv("files_for_pandas/employees.csv")
df[0:4]
# output = None

First Name  Gender Start Date Last Login Time  Salary  Bonus %  \
0    Douglas    Male   8/6/1993        12:42 PM   97308    6.945   
1     Thomas    Male  3/31/1996         6:53 AM   61933    4.170   
2      Maria  Female  4/23/1993        11:17 AM  130590   11.858   
3      Jerry    Male   3/4/2005         1:00 PM  138705    9.340   

  Senior Management       Team  
0              True  Marketing  
1              True        NaN  
2             False    Finance  
3              True    Finance

In [68]:
# df.info()  ; note size of the file

  - **<font color = "blue" > Changing Date and Time column in proper format</font>**

In [69]:
# df["Start Date"].to_date

In [70]:
df["Start Date"] = pd.to_datetime(df["Start Date"])

In [71]:
df["Last Login Time"] = pd.to_datetime(df["Last Login Time"])

 - **<font color = "blue" > Multiple repeating values --> category  </font>**

In [72]:
df["Gender"] = df["Gender"].astype("category")

In [73]:
# df.info()   ; see the difference

**<font color = "olive" >  <u>  Short cut of time format is parse_date during within read_csv() </u> </font>**

[Back to Top](#start)

#### <font color = "navy" > 4.2: Extracting by boolean list </font> <a id="ref_4.2"></a>

In [79]:
%reset -f
import pandas as pd

In [88]:
df = pd.read_csv("files_for_pandas/employees.csv",parse_dates=["Start Date","Last Login Time"])
df["Senior Management"] = df["Senior Management"].astype("category")
df["Gender"] = df["Gender"].astype("category")

  - **<font color = "blue" > Lets say we need only Male from Gender Column </font>**

In [90]:
df["Gender"] == "Male"
output = None

In [92]:
df [  df["Gender"] == "Male"   ]
output = None

         Alternatively

In [97]:
mask = df["Gender"] == "Male"
mask
output = None

In [98]:
df[mask]
output = None

[Back to Top](#start)

#### <font color = "navy" > 4.3: Filtering  with more than 1 CONDITION </font> <a id="ref_4.3"></a>

In [100]:
%reset -f
import pandas as pd

In [150]:
df = pd.read_csv("files_for_pandas/employees.csv",parse_dates=["Start Date","Last Login Time"])
df["Gender"] = df["Gender"].astype("category")
df["Team"] = df["Team"].astype("category")
df[0:4]
output = None

 - **<font color = "blue" >  &, | condition </font>**

In [111]:
m1 = df["Gender"] == "Male"
m2 = df["Senior Management"] == True

In [117]:
df[m1 & m2][0:4]
output = None

In [118]:
df[m1 | m2][0:5]
output = None

 - **<font color = "blue" >  Data or Year as a string </font>**

In [125]:
m3 = df["Start Date"] <= "1990-01-01"
output = None

In [128]:
df[m3][0:6]
output = None

 - **<font color = "blue" >  Mixed Conditions </font>**

In [130]:
m1 = df["Gender"] == "Male"
m2 = df["Senior Management"] == True
m3 = df["Start Date"] <= "1990-01-01"

In [140]:
df [ (m1 & m2) | m3][3:10]
output = None

[Back to Top](#start)

#### <font color = "navy" > 4.4: Multiple OR conditions in single line FOR Single Column </font> <a id="ref_4.4"></a>

<font color = "green" size ="3" >  Useful at the time of multiple "OR condition" <br/>
Instead of creating many boolean series ... we can use .isin() method <br/>
Very convenient when apply many condition on same column</font>

In [170]:
%reset -f
import pandas as pd

In [168]:
df = pd.read_csv("files_for_pandas/employees.csv",parse_dates=["Start Date","Last Login Time"])
df["Gender"] = df["Gender"].astype("category")
df["Start Date"] = df["Start Date"].astype("category")
df.head()
output = None

In [169]:
m4 = df["Team"].isin(["Legal","Finance","Marketing"])
df[m4][0:6]
output = None

[Back to Top](#start)

#### <font color = "navy" > 4.5: Detecting null values; .isnull( ) , .notnull( ) </font> <a id="ref_4.5"></a>

In [ ]:
%reset -f

In [24]:
import pandas as pd
df = pd.read_csv("files_for_pandas/employees.csv",parse_dates=["Start Date","Last Login Time"])
df["Gender"] = df["Gender"].astype("category")
df["Senior Management"] = df["Senior Management"].astype("category")
df[0:4]
output = None

In [26]:
df [df["Team"].isnull()]
output = None

In [30]:
df [df["Team"].notnull()]
output = None

- **<font color = "blue" > Just in case You are worried whether data has NaN and what the position then  </font>**

In [31]:
%reset -f
import pandas as pd
df = pd.read_csv("files_for_pandas/chicago.csv")
df.tail()

Name           Position Title Department  \
32058   ZYGOWICZ,  PETER J           POLICE OFFICER     POLICE   
32059    ZYMANTAS,  MARK E           POLICE OFFICER     POLICE   
32060  ZYRKOWSKI,  CARLO E           POLICE OFFICER     POLICE   
32061  ZYSKOWSKI,  DARIUSZ  CHIEF DATA BASE ANALYST       DoIT   
32062                  NaN                      NaN        NaN   

      Employee Annual Salary  
32058              $87384.00  
32059              $84450.00  
32060              $87384.00  
32061             $113664.00  
32062                    NaN

In [32]:
# first check with .info() method

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32063 entries, 0 to 32062
Data columns (total 4 columns):
Name                      32062 non-null object
Position Title            32062 non-null object
Department                32062 non-null object
Employee Annual Salary    32062 non-null object
dtypes: object(4)
memory usage: 1002.0+ KB


<font color = "olive" >  <u> See total of 32063 row index and 32062 non-nullobject, means one object is null.. Just in case not at the top or bottom then .. here you will go<br/>  
    
</u> </font>

In [41]:
m = df["Name"].isnull()

In [44]:
df[m]
output = None

In [45]:
df[m].index
pass

[Back to Top](#start)

#### <font color = "navy" > 4.6: .between method </font> <a id="ref_4.6"></a>

In [213]:
%reset -f
import pandas as pd

In [214]:
import pandas as pd
df = pd.read_csv("files_for_pandas/employees.csv",parse_dates=["Start Date","Last Login Time"])
df["Gender"] = df["Gender"].astype("category")
df["Senior Management"] = df["Senior Management"].astype("category")
df[0:4]
output = None

 <font color = "olive" >  <u> One way is write separate condition like below </u> </font>

In [215]:
m1 = df["Bonus %"] >= 2.0

In [210]:
m2 = df["Bonus %"] <= 4.0

In [211]:
df [m1 & m2][0:6]
output = None

 <font color = "olive" >  <u> The other way is to use .between( ) method </u> </font>

In [212]:
df [df["Bonus %"].between(2,4)][0:6]
output = None

In [207]:
df  [ df["Start Date"].between("1990-01-1","1992-01-01") ].head(2)
output = None

[Back to Top](#start)

#### <font color = "navy" > 4.7: .duplicated( ) method </font> <a id="ref_4.7"></a>

In [216]:
%reset -f
import pandas as pd

In [237]:
import pandas as pd
df = pd.read_csv("files_for_pandas/employees.csv",parse_dates=["Start Date","Last Login Time"])
df["Gender"] = df["Gender"].astype("category")
df["Senior Management"] = df["Senior Management"].astype("category")
df.sort_values("First Name", ascending = True, inplace = True)
df[0:6]
output = None

In [236]:
df["First Name"].duplicated().head()
output = None

<font color = "olive" >  <u> by default, keep = "first" ; means it takes first time new appearnce as False (never appeard before) and then later same item as true; <br>
so logically when such boolean list is passed to DataFrame, only True's will be shown</u> </font>

In [235]:
df [  df["First Name"].duplicated()  ][0:6]
output = None

<font color = "olive" >  <u> here you can all the Aaron's except the very first one <br>
because only the very first one was False, all others were True</u> </font>

- **<font color = "blue" > How to negate the Boolean list </font>**

In [234]:
df [  ~df["First Name"].duplicated()  ][0:6]
output = None

<font color = "olive" >  <u>  ~       This can make all the True as False and vice versa  </u> </font>

- **<font color = "blue" > How to remove all duplicats no matter where is the position </font>**

In [233]:
df [  ~df["First Name"].duplicated(keep = False)  ]
output = None

<font color = "olive" >  <u>  Without negation symbol ~, this was showing all the duplicated only, taking </u> first and last whatever position always true <br>
now with negation symbol, we are negating all the duplicated . Now only those values whoose duplicated doesn't exit are True</font>

[Back to Top](#start)

#### <font color = "navy" > 4.8: .drop_duplicate( ) method </font>  <a id="ref_4.8"></a>

In [3]:
%reset -f
import pandas as pd

In [4]:
import pandas as pd
df = pd.read_csv("files_for_pandas/employees.csv",parse_dates=["Start Date","Last Login Time"])
df["Gender"] = df["Gender"].astype("category")
df["Senior Management"] = df["Senior Management"].astype("category")
df.sort_values(by = "First Name", ascending = True, inplace = True)
df[0:6]
output = None

 <font color = "olive" >  <u> easy to apply, it acts on the whole Data Frame ; <br>
  keep = "first" ---> keep the first and False other  <br> 
  keep = "last"  ---> keep the last and False other   <br>
  keep = False -----> just remove all duplicates  </u> </font>

In [245]:
df.drop_duplicates(subset=["First Name"],keep = False)
output = None

[Back to Top](#start)

#### <font color = "navy" > 4.9: What are and how many unique items in a Column? </font> <a id="ref_4.9"></a>

In [247]:
%reset -f
import pandas as pd

In [253]:
import pandas as pd
df = pd.read_csv("files_for_pandas/employees.csv",parse_dates=["Start Date","Last Login Time"])
df["Gender"] = df["Gender"].astype("category")
df["Senior Management"] = df["Senior Management"].astype("category")
df.sort_values("First Name", ascending = True, inplace = True)
df[0:6]
output = None

In [254]:
df["Gender"].unique()

[Male, NaN, Female]
Categories (2, object): [Male, Female]

In [255]:
df["Gender"].nunique()

2

In [256]:
df["Gender"].nunique(dropna = False)

3

[Back to Top](#start)

### Ch 5. Data Frames-3  <a id="ch_5"></a>

#### <font color = "navy" > 5.1: set_index( ) and reset_index( ) method: </font>  <a id="ref_5.1"></a>

In [8]:
%reset -f
import pandas as pd
bond = pd.read_csv("files_for_pandas/jamesbond.csv")

In [9]:
bond.head(5)
output = None

 - **<font color = "blue" > Lets say, I want to set "Film" as an index </font>**

In [10]:
bond.set_index(keys = "Film",inplace = True)

In [11]:
bond.head(3)
output = None

 - **<font color = "blue" > Now I replace "Film" index by something else </font>**

In [12]:
bond.set_index("Year").head(3)
output = None

<font color = "olive" >  <u> You can see that , it just through away the "Film" columns </u> </font>

 - **<font color = "blue" > So first reset the index like below </font>**

In [13]:
bond.reset_index(inplace=True)

In [14]:
bond.head(3)
output = None

 - **<font color = "blue" > Now replace it by something else </font>**

In [30]:
bond.set_index(keys = "Year", inplace = True)

In [31]:
bond.head(3)
output = None

[Back to Top](#start)

#### <font color = "navy" > 5.2: Selecting rows and columns in a data Frame </font>  <a id="ref_5.2"></a>

In [1]:
%reset -f
import pandas as pd
bond = pd.read_csv("files_for_pandas/jamesbond.csv",index_col="Film")
bond.sort_index(inplace = True)
bond.head(9)
output = None

 - **<font color = "blue" > Selecting column recape </font>**

In [118]:
# as a series
bond["Year"].head(3)
pass

In [119]:
# as a data frame
bond[["Year"]].head()
pass

 - **<font color = "blue" > Selecting row/rows with string index </font>**
  - **<font color = "blue" > loc[ ] method </font>**

 <font color = "green" size ="3" > Also used for selection range of columns...  </font>

In [120]:
bond.head(3)
output = None

In [121]:
# as a series object
bond.loc["A View to a Kill"]
pass

In [122]:
# as a data frame object
bond.loc[["A View to a Kill"]]
pass

In [123]:
# more than one rows
bond.loc[["A View to a Kill","Casino Royale"]]
output = None

In [9]:
# more than one rows, with  against particular value
bond.loc["A View to a Kill","Actor"]

'Roger Moore'

In [10]:
# ":" symbol for rangle of rows or even columns
bond.loc["A View to a Kill":"A View to a Kill","Year"]

Film
A View to a Kill    1985
Name: Year, dtype: int64

In [65]:
bond.loc["A View to a Kill",["Year","Actor"]]

Year            1985
Actor    Roger Moore
Name: A View to a Kill, dtype: object

In [124]:
bond.loc[["A View to a Kill","Casino Royale"],["Year","Actor"]]
output = None

In [125]:
# ":" used for range of rows and columns both 
bond.loc["A Viw to a Kill":"GoldenEye","Year":"Budget"]
output = None

 - **<font color = "blue" > Selecting row with Numerical index </font>**
  - **<font color = "blue" > iloc[ ] method </font>**

In [126]:
bond.head(5)
output = None

In [127]:
bond.iloc[3]
pass

**<font color = "olive" >  <u> selecting rows with Numeic index, although index is alpha.. </u> </font>**

In [128]:
bond.iloc[[4,1,3]]
output = None

In [129]:
# range of rows against one particular value
bond.iloc[1:5,[1]]
output = None

In [130]:
# range of rows and columns
bond.iloc[1:4,1:3]
output = None

In [6]:
# range of rows and columns
bond.iloc[:,1:7]
output = None

[Back to Top](#start)

#### <font color = "navy" > 5.3: Setting new values in a row or columns... </font>  <a id="ref_5.3"></a>

In [24]:
%reset -f
import pandas as pd
bond = pd.read_csv("files_for_pandas/jamesbond.csv",index_col="Film")
bond.sort_index(inplace=True)
bond.head(4)

Year         Actor         Director  Box Office  Budget  \
Film                                                                            
A View to a Kill      1985   Roger Moore        John Glen       275.2    54.5   
Casino Royale         2006  Daniel Craig  Martin Campbell       581.5   145.3   
Casino Royale         1967   David Niven       Ken Hughes       315.0    85.0   
Diamonds Are Forever  1971  Sean Connery     Guy Hamilton       442.5    34.7   

                      Bond Actor Salary  
Film                                     
A View to a Kill                    9.1  
Casino Royale                       3.3  
Casino Royale                       NaN  
Diamonds Are Forever                5.8

 - **<font color = "blue" >  setting one particular value </font>**

In [28]:
bond.loc["A View to a Kill", "Actor"] = "R.M"
bond.iloc[[0]]

Year Actor   Director  Box Office  Budget  Bond Actor Salary
Film                                                                          
A View to a Kill  1985   R.M  John Glen       275.2    54.5                9.1

 - **<font color = "blue" >  setting values for multiple columns </font>**

<font color = "green" size ="3" >  Idea is to access first .. and then sign via multiple new values in an array</font>

In [31]:
bond.loc["A View to a Kill",["Director","Box Office","Budget"]] = ["Sir J G","275.2 mmmm", "54.5 mmmm"]

In [33]:
bond.loc[["A View to a Kill"]]

Year Actor Director  Box Office     Budget  \
Film                                                           
A View to a Kill  1985   R.M  Sir J G  275.2 mmmm  54.5 mmmm   

                  Bond Actor Salary  
Film                                 
A View to a Kill                9.1

 **<font color = "olive" >  <u> Similiar operations are possible with iloc[ ] method as well </u> </font>**

[Back to Top](#start)

#### <font color = "navy" > 5.4: Setting news values across multiple rows... </font>  <a id="ref_5.4"></a>

In [20]:
%reset -f
import pandas as pd
bond = pd.read_csv("files_for_pandas/jamesbond.csv", index_col="Film")
bond.sort_index(inplace=True)
bond.head(3)
output = None

In [112]:
bond.iloc[[1,3,5]]
pass

In [93]:
bond.iloc[[1,3],[1,2]] = [  ["Sir Daniel Craig","M.C"],["Sir Sean Connery","G.H."]    ]

In [113]:
bond.iloc[[1,3],[1,2]]
output = None

 - **<font color = "blue" >  Change all Sean Connery with "Sir. Sean Connery" </font>**

In [21]:
bond.head(3)
output =None

In [22]:
m1 = bond["Actor"] == "Roger Moore"
m1
output = None

In [23]:
bond[m1]
output = None

In [24]:
bond.loc[m1]
output = None

In [25]:
bond.loc[m1,"Actor"]
pass

<font color = "green" size ="3" >  This is not a separate copy,so "bond.loc[m1]" is a whole new dF.. **AND WHAT WE WANT TO EFFECT** is THE 2nd argument e.g. "Actor"  </font>

In [17]:
bond.loc[m1,"Actor"] = "Mr Roger Moore"

In [26]:
bond.loc[m1]
output = None

**<font color = "olive" >  Keep in mind to use  .loc[ ] for this kind of situation </font>**

[Back to Top](#start)

#### <font color = "navy" > 5.5: Chaning Columns Names </font>  <a id="ref_5.5"></a>

In [107]:
%reset -f
import pandas as pd
bond = pd.read_csv("files_for_pandas/jamesbond.csv", index_col= "Film")
bond.sort_index(inplace=True)
bond.head(3)
output = None

In [106]:
bond.rename(columns = {"Year": "Release Year",
                       "Actor": "Permorfed by",
                       "Budget": "Revenue"
                      }, inplace = True )
output = None

In [108]:
bond.head(2)
pass

**<font color = "olive" >  Similiarly for row string index as well </font>**

- **<font color = "blue" > Just Reminder </font>**

In [109]:
bond.columns
pass

In [110]:
bond.index
pass

[Back to Top](#start)

#### <font color = "navy" > 5.6: Deleting row or columns </font>  <a id="ref_5.6"></a>

In [2]:
%reset -f
import pandas as pd
bond = pd.read_csv("files_for_pandas/jamesbond.csv", index_col="Film")
bond.sort_index(inplace=True)
bond.head()
output = None

In [3]:
bond.drop(columns = ["Year","Actor"])
output = None

In [4]:
bond.drop(index = ["A View to a Kill","Casino Royale","Diamonds Are Forever","Die Another Day"])
output = None

- **<font color = "blue" > Range of Index </font>**

<font color = "green" size ="3" >  Thing to remeber is.. 
**df.index or df.columns are 1-D arrays** ... they have propoer index and every thing else.. <br/>
we can get range with them like :  **df.index[0:3]** or **df.columns[3:8]**.. for any purpose.. <br/>
but here we want to delate so lets do ...

</font>

In [5]:
bond.index[0]
pass

In [6]:
bond.index[0:5]
pass

In [10]:
# for range of rows:
bond.drop(index = bond.index[0:5])
output = None

In [14]:
# for range of columns:
bond.drop(columns=bond.columns[1:3])
output = None

**<font color = "olive" >  Pop method might be useful, it trim the orignal df and return the trimmed portion </font>**

[Back to Top](#start)

#### <font color = "navy" > 5.7: Selecting  n number of small/large values </font>  <a id="ref_5.7"></a>

In [146]:
%reset -f
import pandas as pd
bond = pd.read_csv("files_for_pandas/jamesbond.csv", index_col="Film")
bond.sort_index(inplace=True)
bond.head()
output = None

In [143]:
bond.nlargest(6,columns = "Box Office",keep = "first")
# bond.nsmallest(6,columns = "Box Office",keep = "first")
output = None

**<font color = "blue" > In case we only need, 1d Series </font>**

In [145]:
bond["Box Office"].nlargest(6)
pass

[Back to Top](#start)

#### <font color = "navy" > 5.8: Overall picture  where some particular scanrio is? </font>  <a id="ref_5.8"></a>

In [153]:
%reset -f
import pandas as pd
bond = pd.read_csv("files_for_pandas/jamesbond.csv", index_col="Film")
bond.sort_index(inplace=True)
bond.head()
output = None

In [152]:
m1 = bond["Actor"] == "Roger Moore"
bond.where(m1)
output = None

<font color = "green" size ="3" >  This shows the overall picture where our condition is met rather than just returning the new data frame</font>

[Back to Top](#start)

#### <font color = "navy" > 5.9: Separate copy from df </font>  <a id="ref_5.9"></a>

In [160]:
%reset -f
import pandas as pd
bond = pd.read_csv("files_for_pandas/jamesbond.csv", index_col="Film")
bond.sort_index(inplace=True)
bond.head()
output = None

In [163]:
actr = bond["Actor"].copy()
pass

In [164]:
actr.head(3)
pass

[Back to Top](#start)

#### <font color = "navy" > 5.10: what is .apply() method in pandas context </font>  <a id="ref_5.10"></a>

In [974]:
%reset -f
import pandas as pd
from pandas import DataFrame
df = DataFrame.from_dict(
    {
        'num1' : [1,2,3,4,5], 
        'num2' : [5,10,15,20,25], 
        'num3' : [10,20,30,40,50], 
        'letter' : ['a','b','c','d','e']
    }
)
df
output = None

- **<font color = 'blue' >case-1: .apply() for a single column </font>**

<font color = "green" size ="3" >  Keep in mind, <code>df["num1]</code> is a 1D pandas object , i.e. 
<code>"Series"</code> <br>
    Now the <code>.apply()</code> send element by element and get the result , untill the all the elments in Series are done    
</font>

In [975]:
def single(value):
    print("enement is ")
    print(value)

In [977]:
# df["num1"].apply(single)

- **<font color = 'blue' >case-2: .apply() for a df </font>**

<font color = "green" size ="3" >  For 2D data frame, it passes series by series
</font>

In [979]:
df
output = None

In [980]:
def data_frame1(values):
    print("element is ")
    print(values)
    print(type(values))
    

In [984]:
# df.apply(data_frame1)


<font color = "green" size ="3" >  But here it has two choices, 
 Either go row by row or column by column
</font>

In [986]:
df
output = None

In [987]:
def data_frame1(values):
    print("element is ")
    print(values)
    print(type(values))
    

In [988]:
# df.apply(data_frame1, axis = "columns")

In [990]:
df
output = None

<font color = "green" size ="3" >  And so we have access over the element as well
</font>

In [991]:
def data_frame1(values):
    print(values[0])
    print(values[1])
    print("****************")
    

In [993]:
# df.apply(data_frame1, axis = "columns")
# df.apply(data_frame1, axis = "rows")

- **<font color = 'blue' >case-3: How to use .apply() with lambda function for a df </font>**

In [994]:
%reset -f
import pandas as pd
from pandas import DataFrame
df = DataFrame.from_dict(
    {
        'num1' : [1,2,3,4,5], 
        'num2' : [5,10,15,20,25], 
        'num3' : [10,20,30,40,50], 
        'letter' : ['a','b','c','d','e']
    }
)
df
output = None

<font color = "green" size ="3" >  Lets's say we want to create a new columns at the end of this df,
    Its very necessary to mention the <code>axis=0/1</code> information
</font>

In [995]:
df
output = None

In [999]:
df["new_COL1"] = df.apply(lambda x:  x["letter"] + str(x["num2"]) + " ", axis = "columns")

In [1000]:
df
output = None

In [1001]:
df["new_COL2"] = df.apply(lambda x: x["new_COL1"]*3  , axis = "columns")

In [1002]:
df
output = None

- **<font color = 'blue' >case-3: Using .apply() with lambda function in a for loop </font>**

In [1004]:
%reset -f
import pandas as pd
from pandas import DataFrame
df = DataFrame.from_dict(
    {
        'num1' : [1,2,3,4,5], 
        'num2' : [5,10,15,20,25], 
        'num3' : [10,20,30,40,50], 
        'letter' : ['a','b','c','d','e']
    }
)
df
output = None

In [1005]:
cols = ["num1","num2","num3","letter"]

In [1006]:
i = 0
for name in df:
    i+=1
    df[name + "_COL" + name[-1]] = str(i) + "," + df[name].apply(lambda x: str(x)+" "+name)


In [1007]:
df
output = None

[Back to Top](#start)

#### <font color = "navy" > 5.11: Real example with .apply() method </font>  <a id="ref_5.11"></a>

In [1]:
%reset -f
import pandas as pd
df = pd.read_csv("files_for_pandas/jamesbond.csv", parse_dates=["Year"], index_col="Film")
df.sort_index(inplace=True)
df.head(10)
# output = None

Year           Actor         Director  Box Office  \
Film                                                                            
A View to a Kill      1985-01-01     Roger Moore        John Glen       275.2   
Casino Royale         2006-01-01    Daniel Craig  Martin Campbell       581.5   
Casino Royale         1967-01-01     David Niven       Ken Hughes       315.0   
Diamonds Are Forever  1971-01-01    Sean Connery     Guy Hamilton       442.5   
Die Another Day       2002-01-01  Pierce Brosnan     Lee Tamahori       465.4   
Dr. No                1962-01-01    Sean Connery    Terence Young       448.8   
For Your Eyes Only    1981-01-01     Roger Moore        John Glen       449.4   
From Russia with Love 1963-01-01    Sean Connery    Terence Young       543.8   
GoldenEye             1995-01-01  Pierce Brosnan  Martin Campbell       518.5   
Goldfinger            1964-01-01    Sean Connery     Guy Hamilton       820.4   

                       Budget  Bond Actor Salary  
Film                                              
A View to a Kill         54.5                9.1  
Casino Royale           145.3                3.3  
Casino Royale            85.0                NaN  
Diamonds Are Forever     34.7                5.8  
Die Another Day         154.2               17.9  
Dr. No                    7.0                0.6  
For Your Eyes Only       60.2                NaN  
From Russia with Love    12.6                1.6  
GoldenEye                76.9                5.1  
Goldfinger               18.6                3.2

In [2]:
def sorting_1(n):
    if n < 500:
        return "low"
    if n >=500 and n <=600:
        return "middlw"
    else:
        return "high"

In [3]:
df["Box Office"].apply(sorting_1)
# pass

Film
A View to a Kill                      low
Casino Royale                      middlw
Casino Royale                         low
Diamonds Are Forever                  low
Die Another Day                       low
Dr. No                                low
For Your Eyes Only                    low
From Russia with Love              middlw
GoldenEye                          middlw
Goldfinger                           high
Licence to Kill                       low
Live and Let Die                      low
Moonraker                          middlw
Never Say Never Again                 low
Octopussy                             low
On Her Majesty's Secret Service       low
Quantum of Solace                  middlw
Skyfall                              high
Spectre                              high
The Living Daylights                  low
The Man with the Golden Gun           low
The Spy Who Loved Me               middlw
The World Is Not Enough               low
Thunderball                  

In [45]:
df["Box Office"].apply(sorting_1).value_counts()

low       15
middlw     7
high       4
Name: Box Office, dtype: int64

<font color = "green" size ="3" >  This is how the apply method works on a single columns <br/>
Thing to remember is... Pandas was given a single columns, then with apply method every single value is passed to self defined function. <br/> <br/> Right? Yes <br/> So how each single value is being passed... its definitely row-by-row.. not like the whole column is just passed at once..  <br/> This is what we are going to check in next cells with whole dF</font>

In [46]:
def display_apply_pattern(tmp):
    x = tmp[1]
    y = tmp[2]
    
    print(x,"~~~",y)
    print("next")

<font color = "green" size ="3" >  First and Second entity is stored in x,y and then later just print.. <br/> Just to keep in mind that at back end.. pandas is sending data to our self-defined function in a row-by-row mode <br> 
**Later we have to keep in mind.. axis = "columns" because its its moving across different columns in a paramter**</font>

In [58]:
# df.apply(display_apply_pattern,axis ="columns")
pass

<font color = "Red" size ="3" >  Now we understand the method itself .. so lets apply on our data...</font>

In [54]:
df.head()
output = None

In [50]:
def f(row):
    actr = row[1]
    budget = row[4]
    
    if actr == "Roger Moore":
        return "The best"
    elif actr == "Roger Moore" and budget > 500:
        return "Enjoyable"
    else:
        "No Idea"
    

In [53]:
df.apply(f,axis ="columns")
pass

[Back to Top](#start)

### Ch 6. Working with Text Data  <a id="ch_6"></a>

#### <font color = "navy" > 6.1: Common String methods </font>  <a id="ref_6.1"></a>

In [152]:
%reset -f
import pandas as pd
chicago = pd.read_csv("files_for_pandas/chicago.csv")
chicago["Department"] = chicago["Department"].astype(dtype = "category")
# print(chicago.head())
# chicago.info()
output = None

- **<font color = "blue" > 6.1.1: lower/upper case </font>**

In [11]:
"Hellow World".lower()

'hellow world'

In [16]:
chicago["Name"].str.lower()
output = None

In [20]:
chicago["Name"].str.lower().str.upper()
output = None

- **<font color = "blue" > 6.1.2: title </font>**

In [25]:
"every night I see you I feel".title()

'Every Night I See You I Feel'

In [23]:
chicago["Name"].str.title()
output = None

- **<font color = "blue" > 6.1.3 Length of each index </font>**

In [26]:
len("Boxes")

5

In [28]:
chicago["Name"].str.len()
output = None

[Back to Top](#start)

#### <font color = "navy" > 6.2: Replace methods </font>  <a id="ref_6.2"></a>

In [149]:
%reset -f
import pandas as pd
chicago = pd.read_csv("files_for_pandas/chicago.csv")
chicago.dropna(how="all", inplace=True)
chicago["Department"] = chicago["Department"].astype(dtype = "category")
chicago.tail()
output = None

In [43]:
chicago["Name"].str.replace(" ","_")
output = None

In [45]:
chicago["Employee Annual Salary"].str.replace("$","")
output = None

[Back to Top](#start)

#### <font color = "navy" > 6.3: String with some specific ending or starting or inside, Filtering </font>  <a id="ref_6.3"></a>

In [18]:
%reset -f
import pandas as pd
chicago = pd.read_csv("files_for_pandas/chicago.csv")
chicago.dropna(how="all", inplace=True)
chicago["Department"] = chicago["Department"].astype(dtype = "category")
chicago.tail()
output = None

In [59]:
m1 = chicago["Position Title"].str.lower().str.startswith("POLICE")
chicago[m1]
output = None

In [61]:
m2 = chicago["Position Title"].str.lower().str.endswith("OFFICER")
chicago[~m2]
output = None

<font color = "green" size ="3" >  **Make sure to remove NaN values before. it gets mad with that**</font>

[Back to Top](#start)

#### <font color = "navy" > 6.4: Remove space from left/right sides of a string </font>  <a id="ref_6.4"></a>

In [48]:
%reset -f
import pandas as pd
chicago = pd.read_csv("files_for_pandas/chicago.csv")
chicago.dropna(how="all", inplace=True)
chicago["Department"] = chicago["Department"].astype(dtype = "category")
chicago.tail()
output = None

In [49]:
"    my name is khan   ".lstrip()

'my name is khan   '

In [50]:
"    my name is khan   ".rstrip()

'    my name is khan'

In [51]:
"    my name is khan   ".strip()

'my name is khan'

In [52]:
chicago["Name"] = chicago["Name"].str.strip()
chicago["Name"].head(3)
pass

[Back to Top](#start)

#### <font color = "navy" > 6.5: Split method </font>  <a id="ref_6.5"></a>

In [2]:
%reset -f
import pandas as pd
chicago = pd.read_csv("files_for_pandas/chicago.csv").dropna(how = "all")
chicago["Department"] = chicago["Department"].astype(dtype = "category")
chicago.tail()
output = None

In [5]:
"Hellow World".split(" ")
pass

In [6]:
chicago["Name"].str.split(",").head(3)
output = None

<font color = "green" size ="3" >  **Don't confuse with the commna here like "[AARON,   ELVIA J]"** <br/>
This comman is pandas way to tell left and right objects are different    **</font>

In [7]:
chicago["Name"].str.strip().str.split(",").str.get(0).str.title().value_counts().head(5)
pass

- **<font color = "blue" > n and example paramter available in .strip() method </font>**

In [8]:
%reset -f
import pandas as pd
chicago = pd.read_csv("files_for_pandas/chicago.csv").dropna(how = "all")
chicago["Department"] = chicago["Department"].astype(dtype = "category")
chicago.tail()
output = None

In [9]:
chicago[["alpha","beta"]] =  chicago["Name"].str.strip().str.split(",",expand = True)

 <font color = "olive" >  <u> with expand = True, it gives us a dataframe.. <br/>
 since here it is splitted into 2 , we need to define 2 columns names to store the data like below   </u> </font>

In [10]:
chicago.head(3)
output = None

In [11]:
# chicago["Position Title"].str.strip().str.split(" ",expand = True)
chicago["Position Title"].str.strip().str.split(" ", expand = True, n=1)
output = None

[Back to Top](#start)

### Ch 7.  Introduction to Multi Index Module  <a id="ch_7"></a>

#### <font color = "navy" > 7.1: Difference Between Simple and Multi-level index </font>  <a id="ref_7.1"></a>

In [1]:
%reset -f
import pandas as pd

In [2]:
df1 = pd.read_csv("files_for_pandas/bigmac.csv", parse_dates=["Date"], index_col=["Date"])
df1.sort_index(ascending=True, inplace=True)
df1.head()
pass

<font color = "olive" >  <u> Check the type of this data frame</u>  <br/> It would be simple "DataFrame", the reason is ... just one item is serving as an index </font>

In [3]:
print(type(df1))
print(type(df1.index))
output = None

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.indexes.datetimes.DatetimeIndex'>


<font color = "olive" >  <u> Let's rewrite the stuff , and focus on index</u>  <br/> Because the index_col is an array, so it turned out to be a Multilevel index <br/> Little bit about sorting: we can sort according to one or multiple columns as shown in above and below scenarios </font>

In [4]:
df2 =  pd.read_csv("files_for_pandas/bigmac.csv", parse_dates=["Date"], index_col=["Date","Country"])
df2.sort_index(ascending=[True,True], inplace=True)
df2.head()
output = None

<font color = "olive" >  <u> Time for rechecking the "type" of new DataFrame </u>  </font>

In [5]:
print(type(df2))
print(type(df2.index))
output = None

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.indexes.multi.MultiIndex'>


<font color = "green" size ="3" >  Keep in mind the datatype is DataFrame in both cases., but **.index** is different  **</font>

In [8]:
# df1.info()

In [9]:
# df2.info()

<font color = "olive" >  <u> "df1.info( )" shows .... the index is 'Datetimeindex' with 2  columns  <br/>  "df2.info( )" shows its a MultiIndex and rest of stuff is almost the same </u>  </font>

[Back to Top](#start)

#### <font color = "navy" > 7.2: How to access via "index" in Multi-level DF  </font>  <a id="ref_7.2"></a>

In [134]:
%reset -f
import pandas as pd

In [135]:
df = pd.read_csv("files_for_pandas/bigmac.csv", parse_dates=["Date"], index_col=["Date","Country"])
df.sort_index(ascending=[True,True], inplace=True)
df.head(3)
output = None

- **<font color = "blue" > : style-1 , mention with numeric index </font>**

In [17]:
df.index.get_level_values(0)[0:4]
pass

In [16]:
df.index.get_level_values(1)[0:4]
pass

In [138]:
df.index.get_level_values(0).value_counts().sort_values()
pass

- **<font color = "blue" > : style-2 , mention via string </font>**

In [15]:
df.index.get_level_values("Country")[0:3]
pass

- **<font color = "blue" > : indexing via column </font>**

In [19]:
df[["Price in US Dollars"]][0:4]
# indexing via multilevel column is a question here.. may be we will learn in next chapter.. "group by"
output = None

[Back to Top](#start)

#### <font color = "navy" > 7.3: How to set the index/column names of Multi-index dF  </font>  <a id="ref_7.3"></a>

In [20]:
%reset -f
import pandas as pd

In [33]:
df = pd.read_csv("files_for_pandas/bigmac.csv", parse_dates=["Date"], index_col=["Date","Country"])
df.sort_index(ascending=[True,True], inplace=True)
df2 = df[0:4]
df[0:4]
output = None

In [22]:
df.index.set_names(["Datum","Land"], inplace=True)
df[0:3]
output = None

- **<font color = "blue" > If previously there is no index name at all... ?? </font>**

In [24]:
%reset -f
import pandas as pd
idx = pd.IndexSlice
import numpy as np
#-----------------------------------
def mklbl(prefix, n):
    return ["%s%s" % (prefix, i) for i in range(n)]

miindex = pd.MultiIndex.from_product([mklbl('A', 4),mklbl('B', 2),mklbl('C', 4),mklbl('D', 2)])

micolumns = pd.MultiIndex.from_tuples([('a', 'foo'), ('a', 'bar'),('b', 'goo'), ('b', 'bah')],names=['col1', 'col2'])


dfmi = pd.DataFrame(np.arange(len(miindex) * len(micolumns)).reshape((len(miindex), len(micolumns))),
index=miindex,columns=micolumns).sort_index().sort_index(axis=1)

In [31]:
dfmi.head(3)
output = None

In [30]:
dfmi.index.names
pass

In [27]:
dfmi.index.names = ["aas","bbs","ccs","dds"]

In [29]:
dfmi.head(3)
output = None

- **<font color = "blue" > : for a column name </font>**

In [34]:
df2
output = None

In [35]:
df2.rename(columns={"Price in US Dollars": "$"})
output = None

<font color = "olive" >  <u> This can be exapned to multilevel index names and also for columns...  </u>  </font>

[Back to Top](#start)

#### <font color = "navy" > 7.4: Extract Rows in Multi-level DF  </font>  <a id="ref_7.4"></a>

In [62]:
%reset -f
import pandas as pd
df = pd.read_csv("files_for_pandas/bigmac.csv", parse_dates=["Date"], index_col=["Date","Country"])
df.sort_index(ascending=[True,True], inplace=True)
df[0:50]
output = None

#### <font color = "red" > with .loc[  tuple ]  </font>

- **<font color = "blue" > : style-1, with .loc[ ] method </font>**

In [317]:
df.loc[("2010-01-01","Argentina")]
pass

In [123]:
df.loc[("2010-01-01","Argentina"),"Price in US Dollars"]

Date        Country  
2010-01-01  Argentina    1.84
Name: Price in US Dollars, dtype: float64

In [318]:
df.loc[("2010-01-01","Argentina"),["Price in US Dollars"]]
pass

In [319]:
df.loc[("2010-01-01","Argentina"):("2010-01-01","Britain")]
pass

In [323]:
df.loc[("2010-01-01","Argentina"):("2010-01-01","Britain"),["Price in US Dollars"]]
output = None

#### <font color = "red" > with .loc[  and idx ]  </font>

In [40]:
idx = pd.IndexSlice

```
df.loc[ horizontal_index , vertical_columns ]
df.loc[ idx[horizontal_index] , idx[vertical_columns]  ]
```

- **<font color = "blue" > : How to access: "2010-01-01" and "Argentina" </font>**

In [50]:
df.loc[    idx["2010-01-01","Argentina"],   "Price in US Dollars"     ]
pass

- **<font color = "blue" > : How to access: "2010-01-01" and "Argentina","Australia","Brazil","Britain" </font>**

In [49]:
df.loc[    idx["2010-01-01",["Argentina","Australia","Brazil","Britain"]  ] ,   ["Price in US Dollars"]     ]
output = None

- **<font color = "blue" > : How to access: "2010-01-01" and "Argentina" to "China" </font>**

In [61]:
df.loc[    idx["2010-01-01","Argentina":"China"  ] ,   ["Price in US Dollars"]     ]
output = None

- **<font color = "blue" > : How to access: "2010-01-01" & "2010-07-01" and "Argentina" to "China" </font>**

In [54]:
df.loc[    idx[["2010-01-01","2010-07-01"],"Argentina":"China"  ] ,   ["Price in US Dollars"]     ]
output = None

- **<font color = "blue" > : How to access: "2010-01-01" - "2012-01-01" and "Argentina" to "China" </font>**

In [57]:
df.loc[    idx[ "2010-01-01":"2012-01-01","Argentina":"China"  ] ,   ["Price in US Dollars"]     ]
output = None

- **<font color = "blue" > : How to access: all dates (outer layer) and "Argentina" to "Brazil" </font>**

In [60]:
df.loc[    idx[ :,"Argentina":"Brazil"  ] ,   ["Price in US Dollars"]     ]
output = None

#### <font color = "red" > with .iloc[  ]  </font>

- **<font color = "blue" > : style-2, with .iloc[ ] method </font>**

In [324]:
df[0:4]
output = None

In [325]:
df.iloc[3:8,[0]]
output = None

[Back to Top](#start)

#### <font color = "navy" > 7.5: Extract Rows in Multi-level DF (example_2)  </font>  <a id="ref_7.5"></a>

In [117]:
%reset -f
import pandas as pd
idx = pd.IndexSlice
import numpy as np

In [123]:
def mklbl(prefix, n):
    return ["%s%s" % (prefix, i) for i in range(n)]

miindex = pd.MultiIndex.from_product([mklbl('A', 4),mklbl('B', 2),mklbl('C', 4),mklbl('D', 2)])

micolumns = pd.MultiIndex.from_tuples([('a', 'foo'), ('a', 'bar'),('b', 'goo'), ('b', 'bah')],names=['col_a', 'col_b'])


dfmi = pd.DataFrame(np.arange(len(miindex) * len(micolumns)).reshape((len(miindex), len(micolumns))),
index=miindex,columns=micolumns).sort_index().sort_index(axis=1)

In [133]:
# dfmi.head(10)

- **<font color = "blue" > : index "A0", "BO"... then sub_index "C0","C1","C2" ... AND Column "foo" </font>**

In [129]:
dfmi.loc[    idx["A0","B0",["C0","C1","C2"]] , idx[:,"foo"]  ]
output = None

- **<font color = "blue" > : index "A0" --> "A2"... then sub_index "B0"  --> "B1" ... AND <br/>
 Columns: <br/> outerlayer(col_a)  all.. which is a and b,
 <br/>   one layer down: only bar and bah  </font>**

In [130]:
dfmi.loc[    idx["A0":"A2","B0":"B1","C0":"C2"] , idx[:,["bar","bah"]]  ]
output = None

- **<font color = "blue" > : with some range index  </font>**

In [132]:
dfmi.loc[    idx["A0":"A2","B0":"B1","C0":"C2"] , idx["a":"b",["bar","bah"]]  ]
output = None

[Back to Top](#start)

#### <font color = "navy" > 7.6: Taking transpose of Multi-level dF  </font>  <a id="ref_7.6"></a>

In [326]:
%reset -f
import pandas as pd
df = pd.read_csv("files_for_pandas/bigmac.csv", parse_dates=["Date"], index_col=["Date","Country"])
df.sort_index(ascending=[True,True], inplace=True)
df[0:4]
output = None

<font color = "olive" >  <u> Simple we can take transpose like this way: </u> </font>

In [327]:
t = df.transpose()
t
output = None

[Back to Top](#start)

#### <font color = "navy" > 7.7: Swapping the indexes levels in Multi...  </font>  <a id="ref_7.7"></a>

In [64]:
%reset -f
import pandas as pd
idx = pd.IndexSlice
import numpy as np
#--------------------------------
def mklbl(prefix, n):
    return ["%s%s" % (prefix, i) for i in range(n)]

miindex = pd.MultiIndex.from_product([mklbl('A', 4),mklbl('B', 2),mklbl('C', 4),mklbl('D', 2)])

micolumns = pd.MultiIndex.from_tuples([('a', 'foo'), ('a', 'bar'),('b', 'goo'), ('b', 'bah')],names=['col1', 'col2'])


dfmi = pd.DataFrame(np.arange(len(miindex) * len(micolumns)).reshape((len(miindex), len(micolumns))),
index=miindex,columns=micolumns).sort_index().sort_index(axis=1)

In [74]:
dfmi.head(8)
output = None

In [75]:
dfmi.index.names
pass

In [67]:
dfmi.index.names = ['aaas','bbbs','cccs','dddds']

In [76]:
dfmi.index.names
pass

In [77]:
dfmi.head(3)
output = None

In [72]:
dfmi = dfmi.swaplevel('bbbs', 'aaas')

In [78]:
dfmi.head(3)
output = None

[Back to Top](#start)

#### <font color = "navy" > 7.8: stack and unstack methods the dF </font>  <a id="ref_7.8"></a>

#### <font color = "navy" > stack method  </font>

- **<font color = "blue" > 7.7.1: stack() </font>**

In [87]:
%reset -f
import pandas as pd
world = pd.read_csv("files_for_pandas/worldstats.csv", index_col=["country","year"])
world.sort_index(inplace=True)
world.head()
output = None

 - **<font color = "blue" > 7.7.1: stack() method make the data very flat... just through out of any kind of data frame </font>**

In [88]:
st = world.stack()
st.head(4)
pass

 - **<font color = "blue" > Now iterate through st </font>**

In [89]:
st.loc["Afghanistan",1960]
pass

In [90]:
st.loc["Afghanistan",1960,"GDP"]
pass

 - **<font color = "blue" > How to make a data frame of this extrcated chuck</font>**

In [91]:
stt = st.loc["Afghanistan",1960].to_frame()

In [92]:
stt.rename(columns={0: "Numbers"})
output = None

#### <font color = "navy" > unstack method  </font>

In [103]:
%reset -f
import pandas as pd
a = pd.read_csv("files_for_pandas/worldstats.csv", index_col=["country","year"])
a.sort_index(ascending=True, inplace=True)
a.head(4)
output = None

In [104]:
b = a.stack()
b.head()
pass

<font color = "olive" >  <u> First unstacking will just convert back and then it goes on left to right</u> </font>

In [105]:
b.unstack()[0:3]
output = None

 - **<font color = "blue" > Look at the argumets of unstack( ) </font>**

<font color = "olive" >  <u> We can use either index or the name directly... and it will appear as a columns in unstacked data </u> </font>

In [107]:
# b.unstack("country") or
b.unstack(0)[0:2]
output = None

In [99]:
b.unstack(1)
b.unstack("year")[0:4]
output = None

 - **<font color = "blue" > if we keep going with unstack( ) </font>**

<font color = "olive" >  <u> Keep going will ultimately convert the whole stuff into series ... </u> </font>

In [340]:
b.unstack().unstack().unstack()[0:8]
pass

 - **<font color = "blue" > We can set the levels for unstacking  </font>**

In [341]:
b.head()
pass

<font color = "olive" >  <u> with the level argument, we can make it similiar like multilevel df </u> </font>

In [342]:
b.unstack(level=[2,1]).head()
output = None

[Back to Top](#start)

#### <font color = "navy" > 7.9: pivot the data with pivot method  </font>  <a id="ref_7.9"></a>

In [148]:
%reset -f
import pandas as pd
s = pd.read_csv("files_for_pandas/salesmen.csv", parse_dates=["Date"])
s["Salesman"] = s["Salesman"].astype("category")
s.sort_index(ascending=True, inplace=True)
s.head(6)
output = None

In [149]:
piv_data = s.pivot(index="Date", columns="Salesman",values="Revenue")
piv_data.head()
output = None

[Back to Top](#start)

#### <font color = "navy" > 7.10: Slightly different: pivot_table( ) method for more universal use </font>  <a id="ref_7.10"></a>

In [150]:
%reset -f 
import pandas as pd
f = pd.read_csv("files_for_pandas/foods.csv")
f.head()
# output = None

First Name  Gender          City Frequency       Item  Spend
0      Wanda  Female      Stamford    Weekly     Burger  15.66
1       Eric    Male      Stamford     Daily    Chalupa  10.56
2    Charles    Male      New York     Never      Sushi  42.14
3       Anna  Female  Philadelphia      Once  Ice Cream  11.01
4    Deborah  Female  Philadelphia     Daily    Chalupa  23.49

 - **<font color = "blue" > Start with something very simple  </font>**

In [145]:
f.pivot_table(values="Spend",index="Gender",columns="City", aggfunc="sum")
output = None

 - **<font color = "blue" > bit more detailed now...  </font>**

In [142]:
f.pivot_table(values="Spend",index=["Gender","Item"],columns="City", aggfunc="mean")
output = None

 - **<font color = "blue" > even further ...  </font>**

In [152]:
f.pivot_table(values="Spend",index=["Gender","Item"],columns=["Frequency","City"], aggfunc="mean").head()
output = None

[Back to Top](#start)

#### <font color = "navy" > 7.11: Reducing the aggregated date to simple tabular form with pd.melt( ) </font>  <a id="ref_7.11"></a>

In [350]:
%reset -f
import pandas as pd
q = pd.read_csv("files_for_pandas/quarters.csv")
q.head()
output = None

In [351]:
q.pivot_table(values=["Q1","Q2","Q3","Q4"],index=["Salesman"])
output = None

In [352]:
a1 = pd.melt(frame=q, id_vars="Salesman")
a1.head()
output = None

In [353]:
a2 = a1.set_index(["variable","Salesman"])
a2.head()
output = None

[Back to Top](#start)

### Ch 8.  Grouping via .groupby( )method  <a id="ch_8"></a>

#### <font color = "navy" > 8.1: what is groupby method in general </font>  <a id="ref_8.1"></a>

In [36]:
%reset -f
import pandas as pd
f = pd.read_csv("files_for_pandas/fortune1000.csv", index_col="Rank")
f.head(8)
output = None

<font color = "olive" >  <u> So,now we will call a method.. groupby on this dF "f"   </u> </font>

In [37]:
gss = f.groupby(by= "Sector")

<font color = "olive" >  <u> Now the question is , what is groups.head(1) <br/> First understand the dynamics of data ,  after making the groups... There are many sectors ... which are grouped.. and in each sector... there are many industries... so the question is .. how many sectors are in total </u> </font>

In [38]:
len(gss)

21

<font color = "olive" >  <u> One easy way to check it is using nunique( ) function </u> </font>

In [39]:
f.nunique()
pass

<font color = "olive" >  <u> So total 21 groups... and now companies/industries in each group </u> </font>

In [40]:
gss.size()
pass

<font color = "olive" >  <u> We can also achieve the same thing via .value_count( ) on orignal dF </u> </font>

In [41]:
f["Sector"].value_counts()
pass

 - **<font color = "blue" > Best approach to each overall situation in grouping...  </font>**

In [43]:
gss.nunique()
output = None

[Back to Top](#start)

#### <font color = "navy" > 8.2: How to extract each sector </font> <a id="ref_8.2"></a>

In [11]:
%reset -f
import pandas as pd
f = pd.read_csv("files_for_pandas/fortune1000.csv", index_col="Rank")
gss = f.groupby(by= "Sector")
f.head(8)
output = None

In [86]:
gss.size()
pass

In [87]:
# groups.get_group("Transportation")
gss.get_group("Telecommunications")
output = None

<font color = "olive" >  <u> Take it as an opportnity and find the type of orignal and as well as groupby dF </u> </font>

In [88]:
print(type(f))
print(type(gss))
pass

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.groupby.groupby.DataFrameGroupBy'>


 - **<font color = "blue" > One hunting question,,,, then what is groups.head(1)  </font>**

In [89]:
gss.head(1)
output = None

<font color = "olive" >  <u> I think, this is a sorted data taken from all sectors ... as taking the highest "Revenue" company/industry in that sector... </u>   <br/> so two question... <br/> why only 21 company/industries .... 2 reasons   <br/>  
1) head(1) ... 1 is indicating that choose only one and its is internally sorted according to "Revenue" <br/>
2) and why "Revenue"... may be the reason is its first numeric columns
    
<br/> We can somehow use groups.first() or .last() method to double check...    
</font>

In [13]:
# groups.last()
# gss.first()
# output = None

 - **<font color = "blue" >We can also get the index of each sector... for using in iteration  </font>**

In [16]:
gss.groups
pass

In [1]:
f.groups.keys()

NameError: name 'f' is not defined

 <font color = "olive" >  <u> Now lets iterate via .loc[ ] why... b/c its not numeric .. we use "Rank" as an index </u> </font>

In [92]:
f.loc[57]
pass

[Back to Top](#start)

#### <font color = "navy" > 8.3: Now , what methods are available to this groupby object </font>  <a id="ref_8.3"></a>

In [152]:
%reset -f
import pandas as pd
f = pd.read_csv("files_for_pandas/fortune1000.csv", index_col="Rank")
gss = f.groupby(by= "Sector")
f.head(8)
output = None

<font color = "olive" >  <u> So it makes sense , it will  show up  all the numeric columns only .. makes sense... < /font>

In [150]:
gss.sum()
gss.mean()
output = None

<font color = "olive" >  <u> We can also calculate the same thing via following or one or multiple columns < /font>

In [44]:
gss[["Revenue","Profits"]].mean()
output = None

 - **<font color = "blue" >We can also use .agg( ) method for custamize stuff  </font>**

In [148]:
f.head(4)
output = None

In [147]:
gss.agg({"Revenue":"sum", 
        "Profits": "mean",
        "Employees": ["max","min","mean"]
        })
output = None

[Back to Top](#start)

#### <font color = "navy" > 8.4: Grouping via multiple columns </font> <a id="ref_8.4"></a>

In [46]:
%reset -f
import pandas as pd
f = pd.read_csv("files_for_pandas/fortune1000.csv", index_col="Rank")
f.head(8)
output = None

In [47]:
G_ss = f.groupby(by = ["Sector","Industry"])
len(G_ss)
pass

In [48]:
G_ss.size()
pass

In [49]:
G_ss.sum()
output = None

- **<font color = "blue" > Now how to extrac the multilevel groups  </font>**

<font color = "olive" >  <u> We must provide a tuple now </font>

```
G_ss.get_group(tuple)
G_ss.get_group(  ("first identifier ","2nd identifier")    )
```

In [64]:
G_ss.get_group(   ("Energy","Petroleum Refining")  )
# we can do similiar thing by multindex as well
output = None

In [61]:
G_ss.nunique().head()
output = None

<font color = "olive" >   Below script us to show that... groupby object is like a key_value pair, so we can loop through with two labels in for loop </font>

In [ ]:
new_df = pd.DataFrame(columns=df.columns)
for name,group in f:
    new_df = new_df.append(group)

<font color = "olive" >   In the follwing code, it will sort and pick the highest value according to "Revenue" column and then insert it into the new dF... </font>

In [63]:
dF = pd.DataFrame(columns=f.columns)
for index,data in G_ss:
#     i1,i2 = index[0],index[1]
    x = data.nlargest(1,"Revenue")
    dF = dF.append(x)
dF
output = None

[Back to Top](#start)

#### <font color = "navy" > 8.5: Iterating through groupby( ) </font>  <a id="ref_8.5"></a>

In [2]:
%reset -f
import pandas as pd
f = pd.read_csv("files_for_pandas/fortune1000.csv", index_col="Rank")
f.head(8)
gss = f.groupby(by = "Sector")
print(type(gss))
gss.get_group("Technology").head(2)
output = None

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>


In [3]:
dF = pd.DataFrame(columns=f.columns)

In [5]:
for index_info, data in gss:
    x = data.nlargest(1,"Revenue")
    dF = dF.append(x)
dF
pass

[Back to Top](#start)

### Ch 9.  Merging, Joining and concatination  <a id="ch_9"></a>

#### <font color = "navy" > 9.1: Vertical Concatination </font>  <a id="ref_9.1"></a>

In [7]:
%reset -f
import pandas as pd
week1 = pd.read_csv("files_for_pandas/Restaurant - Week 1 Sales.csv")
week2 = pd.read_csv("files_for_pandas/Restaurant - Week 2 Sales.csv")
foods = pd.read_csv("files_for_pandas/Restaurant - Foods.csv")
customers = pd.read_csv("files_for_pandas/Restaurant - Customers.csv")

In [20]:
week1.head()
output = None

In [19]:
week2.head()
output = None

In [12]:
final = pd.concat(objs=[week1,week2])

In [18]:
final.tail()
output = None

In [15]:
# but if we look at len()
len(final)

500

 <font color = "olive" >  <u> Here we can use one tag "ignore_index" </u> </font>

In [17]:
pd.concat(objs=[week1,week2],ignore_index=True)
output = None

[Back to Top](#start)

#### <font color = "navy" > 9.2: Adding another layer of before index </font>  <a id="ref_9.2"></a>

In [21]:
%reset -f
import pandas as pd
week1 = pd.read_csv("files_for_pandas/Restaurant - Week 1 Sales.csv")
week2 = pd.read_csv("files_for_pandas/Restaurant - Week 2 Sales.csv")
foods = pd.read_csv("files_for_pandas/Restaurant - Foods.csv")
customers = pd.read_csv("files_for_pandas/Restaurant - Customers.csv")

In [31]:
week1.head(2)
output = None

In [30]:
week2.head(2)
output = None

In [29]:
df = pd.concat(objs=[week1,week2],keys=["week1","week2"])
df
output = None

 <font color = "olive" >  <u> So here it make sense ... don't use ignore_index = True </u> </font>

[Back to Top](#start)

#### <font color = "navy" > 9.3: Directly append one data set  </font>  <a id="ref_9.3"></a>

In [32]:
%reset -f
import pandas as pd
week1 = pd.read_csv("files_for_pandas/Restaurant - Week 1 Sales.csv")
week2 = pd.read_csv("files_for_pandas/Restaurant - Week 2 Sales.csv")

In [37]:
week1.append(other=week2,ignore_index=True)
output = None

[Back to Top](#start)

#### <font color = "navy" > 9.4: Inner and Outer Joins ( Unions and Intersections of two data sets )  </font>  <a id="ref_9.4"></a>

In [175]:
%reset -f
import pandas as pd
week1 = pd.read_csv("files_for_pandas/Restaurant - Week 1 Sales.csv")
week2 = pd.read_csv("files_for_pandas/Restaurant - Week 2 Sales.csv")
foods = pd.read_csv("files_for_pandas/Restaurant - Foods.csv")
customers = pd.read_csv("files_for_pandas/Restaurant - Customers.csv")

- **<font color = "blue" > 9.4.1: inner join / intersection like </font>**

In [176]:
week1.head(3)
output = None

In [177]:
week2.head(3)
output = None

In [178]:
union1 = week1.merge(right=week2,how = "inner", on=["Customer ID","Food ID"])
union1
output = None

<font color = "olive" >  <u> The on feature is only used when both data sets have same columns names </u> </font>

In [179]:
union2 = week1.merge(right=week2,how = "inner", on=["Customer ID"],indicator=True)
union2[0:5]
output = None

<font color = "olive" >  <u> The difference is : <br/> case-1: When both columns are matched its considering as a union based on our on=["..",".."] array  ; <br/> case-2: only Customer ID is being seached as a pivot item and result is shown in two different columns </u> </font>

In [180]:
# we can chaging suffexes for better display...
union3 = week1.merge(right=week2,how = "inner", on=["Customer ID"],indicator=True, suffixes=["-week1","-week2"])
union3[0:5]
output = None

In [181]:
week1[week1["Customer ID"] == 503]
pass

In [182]:
week2[week2["Customer ID"] == 503]
pass

<font color = "olive" >  <u> Method just repeat 5 , index number 3 and 4 in union-3 to maintain tabular dimension </u> </font>

- **<font color = "blue" > 9.4.2: outer join / silimiar to union of sets </font>**

In [183]:
%reset -f
import pandas as pd
week1 = pd.read_csv("files_for_pandas/Restaurant - Week 1 Sales.csv")
week2 = pd.read_csv("files_for_pandas/Restaurant - Week 2 Sales.csv")
foods = pd.read_csv("files_for_pandas/Restaurant - Foods.csv")
customers = pd.read_csv("files_for_pandas/Restaurant - Customers.csv")

In [184]:
week1.head(3)
output = None

In [185]:
week2.head(3)
output = None

In [186]:
# because names of columns are same we can still use "on" function
merged = pd.merge(left= week1,right=week2,how = "outer", on = "Customer ID" ,suffixes=[" - week1"," - week2"], indicator=True)
merged[2:8]
# because this is union so it can take every thing...
output = None

In [187]:
# then we can go for value_counts() method

In [188]:
merged["_merge"].value_counts()
output = None

In [189]:
# Let's have right_only and left_only ....
merged [ merged["_merge"].isin(["left_only","right_only"])] 
output = None

[Back to Top](#start)

#### <font color = "navy" > 9.5: Left Join , its like Horizontal concatination technique with more attributes </font>  <a id="ref_9.5"></a>

In [206]:
%reset -f
import pandas as pd
week1 = pd.read_csv("files_for_pandas/Restaurant - Week 1 Sales.csv")
week2 = pd.read_csv("files_for_pandas/Restaurant - Week 2 Sales.csv")
foods = pd.read_csv("files_for_pandas/Restaurant - Foods.csv")
customers = pd.read_csv("files_for_pandas/Restaurant - Customers.csv")

- **<font color = "blue" >  Example -1 </font>**

In [209]:
week1.head()
output = None

In [210]:
week2.head()
output = None

In [211]:
week1.merge(right=week2,how = "left",on = "Customer ID", sort=True)[0:5]
output = None

<font color = "olive" >  <u> Base is week1 on which the .merge operation is applied  <br/> 
its searching "Customer ID ==3" in Food ID_x ... values found 3 and for Food ID_y value found is NaN <br/>
Lets check..    </u> </font>

In [212]:
week1  [week1["Customer ID"] == 3]
output = None

In [213]:
week2  [week2["Customer ID"] == 3]
output = None

- **<font color = "blue" >  Example -2 </font>**

In [214]:
week1.head()
output = None

In [215]:
foods.head()
output = None

In [216]:
week1.merge(right=foods,how = "left",on = "Food ID", sort=True)
output = None

[Back to Top](#start)

#### <font color = "navy" > 9.6: Situation when columns names are different.. how to merge? </font>  <a id="ref_9.6"></a>

In [2]:
%reset -f
import pandas as pd
week1 = pd.read_csv("files_for_pandas/Restaurant - Week 1 Sales.csv")
week2 = pd.read_csv("files_for_pandas/Restaurant - Week 2 Sales.csv")
foods = pd.read_csv("files_for_pandas/Restaurant - Foods.csv")
customers = pd.read_csv("files_for_pandas/Restaurant - Customers.csv")

In [230]:
week2.head()
output = None

In [227]:
customers.head()
output = None

In [228]:
week2.merge(right=customers,how = "left", left_on="Food ID", right_on="ID", sort=True)
# so now its keeping "Food ID" and "ID".. which are just duplicates.... we can remove one of them....
output = None

In [229]:
week2.merge(right=customers,how = "left", left_on="Food ID", right_on="ID", sort=True).drop("ID", axis = "columns")
output = None

- **<font color = "blue" >  Changing the columns arrangment of dF </font>**

In [3]:
df = week2.merge(right=customers,how = "left", left_on="Food ID", right_on="ID", sort=True)
df.head(5)
output = None

In [74]:
new_order = [3,2,0,1,4,5,6,7]
output = None

In [73]:
df[df.columns[new_order]]
output = None

[Back to Top](#start)

#### <font color = "navy" > 9.7: merging by index </font>  <a id="ref_9.7"></a>

<font color = "olive" >  <u> lets merge food with week1 </u> </font>

In [17]:
%reset -f
import pandas as pd
week1 = pd.read_csv("files_for_pandas/Restaurant - Week 1 Sales.csv")
week2 = pd.read_csv("files_for_pandas/Restaurant - Week 2 Sales.csv")
foods = pd.read_csv("files_for_pandas/Restaurant - Foods.csv", index_col="Food ID")
customers = pd.read_csv("files_for_pandas/Restaurant - Customers.csv", index_col="ID")

In [18]:
foods.head()
output = None

In [19]:
customers.head()
output = None

In [20]:
week1.head()
output = None

In [21]:
tmp = week1.merge(right=customers,how = "left",left_on="Customer ID",right_index=True)
tmp.head()
output = None

<font color = "olive" >  <u> Now merging this result with the foods dF </u> </font>

In [22]:
foods.head()
output = None

In [23]:
sales = tmp.merge(right=foods,how = "left",left_on="Food ID", right_index=True)
sales
output = None

[Back to Top](#start)

### Ch 10.  Input and Output Module  <a id="ch_10"></a>

#### <font color = "navy" > 10.1: Accessing a URL data in Pandas and actively converting to list,series or comman separated data </font>  <a id="ref_10.1"></a>

In [ ]:
import pandas as pd

df = pd.read_csv(URL)
df.head()
output = None

- **<font color = "blue" > 10.1.1: conversion to List </font>**

In [4]:
df["Child's First Name"].tolist()
output =None

- **<font color = "blue" > 10.1.2: conversion to Data Frame </font>**

In [5]:
df["Child's First Name"].to_frame()
output =None

- **<font color = "blue" > 10.1.3: conversion to coma separated data </font>**

In [7]:
#step-1, for understanding
[    i for i in df["Child's First Name"]     ]
output = None

In [41]:
#step-2, for understanding
# for i in df["Child's First Name"]:
#     print(i+",",end = "")

In [42]:
",".join( i for i in df["Child's First Name"]  )
pass

[Back to Top](#start)

#### <font color = "navy" > 10.2: Writing csv file and export it... with pd.read_cev() method </font>  <a id="ref_10.2"></a>

In [47]:
%reset -f
import pandas as pd
URL = "https://data.cityofnewyork.us/api/views/25th-nujf/rows.csv"
df = pd.read_csv(URL)
df.head()
output =None

In [48]:
df.to_csv("this file.csv",sep=",",columns=["Child's First Name","Count","Rank"] )
pass

[Back to Top](#start)

#### <font color = "navy" > 10.3: Importing excel file </font>  <a id="ref_10.3"></a>

In [58]:
%reset -f
import pandas as pd

- **<font color = "blue" > : Excel file with just one sheet </font>**

In [67]:
excel_single = pd.read_excel("files_for_pandas/Data - Single Worksheet.xlsx")
excel_single.head()
output = None

- **<font color = "blue" > : Excel file with more than one sheet </font>**

In [61]:
excel_multi = pd.read_excel("files_for_pandas/Data - Multiple Worksheets.xlsx",sheet_name=[0,1])

In [64]:
excel_multi[0]
output = None

In [66]:
excel_multi[1]
output = None

[Back to Top](#start)

#### <font color = "navy" > 10.4: Writing file in Excel format </font>  <a id="ref_10.4"></a> 

In [ ]:
%reset -f
import pandas as pd
URL = "https://data.cityofnewyork.us/api/views/25th-nujf/rows.csv"
df = pd.read_csv(URL)
df.head()
output = None

<font color = "olive" >  <u> Step-1: <br/> Name of expected file ad store it in a variabke; remember putting the **extension** </u> </font>

In [85]:
output = pd.ExcelWriter("excel_out.xlsx")

<font color = "olive" >  <u> Step-2: <br/>Same like perl, define whats ever data will going out:: through a $fh variables  </u> </font>

In [86]:
fh_out_f = df [df["Gender"] == "FEMALE"]
fh_out_m = df [df["Gender"] == "MALE"]

<font color = "olive" >  <u> Step-3: <br/> Write in the file via file handles using .to_excelWriter()  </u> </font>

In [87]:
fh_out_f.to_excel(output, sheet_name="girls", index=False)
fh_out_m.to_excel(output, sheet_name="boys", index=False)

<font color = "olive" >  <u> Step-4: <br/> Physically creating and saving on location with .save() method  </u> </font>

In [88]:
output.save()

[Back to Top](#start)

### Ch 11.  Introduction to plotting with matplotlib <a id="ch_11"></a>

#### <font color = "navy" > 11.1: Getting stock data and plot it simply </font>   <a id="ref_11.1"></a> 

In [13]:
%reset -f
import pandas as pd
from pandas_datareader import data
import matplotlib.pyplot as plt
%matplotlib inline

In [14]:
amzn = data.DataReader(name = "AMZN", data_source="yahoo", start="2017-01-01", end="2018-01-01")
amzn.head()
output = None

- **<font color = "blue" > Just try apply() method </font>**

In [12]:
# amzn.plot()

- **<font color = "blue" > Now select one columns and apply this method, style-1  </font>**

In [11]:
# amzn.plot(y="High")

In [15]:
# amzn[["High","Low"]].plot()

[Back to Top](#start)

#### <font color = "navy" > 11.2: Template selection and plotting types </font>  <a id="ref_11.2"></a> 

In [3]:
%reset -f
import pandas as pd
from pandas_datareader import data
import matplotlib.pyplot as plt
%matplotlib inline

In [6]:
amzn = data.DataReader(name="AMZN", data_source="yahoo", start="2017-01-01", end="2018-01-01")
amzn.head()

High         Low        Open       Close   Volume  \
Date                                                                  
2017-01-03  758.760010  747.700012  757.919983  753.669983  3521100   
2017-01-04  759.679993  754.200012  758.390015  757.179993  2510500   
2017-01-05  782.400024  760.260010  761.549988  780.450012  5830100   
2017-01-06  799.440002  778.479980  782.359985  795.989990  5986200   
2017-01-09  801.770020  791.770020  798.000000  796.919983  3440100   

             Adj Close  
Date                    
2017-01-03  753.669983  
2017-01-04  757.179993  
2017-01-05  780.450012  
2017-01-06  795.989990  
2017-01-09  796.919983

<font color = "olive" >  <u> Available templates </font>

In [14]:
plt.style.available
pass

<font color = "olive" >  <u> Try , "fivethirtyeight"  </font>

In [16]:
plt.style.use("fivethirtyeight")
# amzn.plot()

<font color = "olive" >  <u> Try , "ggplot"  </font>

In [17]:
plt.style.use("ggplot")
# amzn.plot()

<font color = "olive" >  <u> Try , "dark_background"  </font>

In [18]:
plt.style.use("dark_background")
# amzn.plot()

[Back to Top](#start)

#### <font color = "navy" > 11.3: Different types of plots </font>  <a id="ref_11.3"></a> 

In [7]:
%reset -f
import pandas as pd
from pandas_datareader import data
import matplotlib.pyplot as plt
%matplotlib inline

In [8]:
apl = data.DataReader(name = "AAPL", data_source="yahoo",start="2017-01-01", end="2018-01-01")
apl.head()
output = None

In [9]:
def sorting_on_apply(n):
    if n <=140:
        return "Poor"
    elif n > 140 and n <= 150:
        return "Ok type"
    else :
        return "Good"

In [11]:
plt.style.use("ggplot")
# apl["High"].apply(sorting_on_apply).value_counts().plot(kind = "line")


In [12]:
# apl["High"].apply(sorting_on_apply).value_counts().plot(kind = "barh", legend = True)

In [13]:
# apl["High"].apply(sorting_on_apply).value_counts().plot(kind = "bar", legend = True)

In [14]:
# apl["High"].apply(sorting_on_apply).value_counts().plot(kind = "pie", legend = True)

In [ ]:
# ### <font color = "navy" > 3.1: Shared methods and attributes with Series objects </font>

In [ ]:
# <font color = "olive" >  <u> Her so overall its a 2D object</u> </font>

In [ ]:
#  - **<font color = "blue" > 3.1.2: .values attributes </font>**

In [119]:
df = pd.DataFrame(columns= f.columns)
df

Empty DataFrame
Columns: [Company, Sector, Industry, Location, Revenue, Profits, Employees]
Index: []